/**
 * RENGU — Feature Registry
 * 5000+ fitur untuk WhatsApp MD Bot
 */
;(function(){
'use strict'

const R = []
let _id = 1

function f(cat, cmd, name, desc, type, extra) {
  R.push({ id: _id++, cat, cmd, name, desc, type: type||'basic', ...extra })
}
function batch(cat, arr, type) {
  arr.forEach(([cmd, name, desc]) => f(cat, cmd, name, desc||name, type||'basic'))
}

// ══════════════════════════════════════════
// 1. TOOLS & UTILITY  ~280 fitur
// ══════════════════════════════════════════
batch('tools', [
  ['ping',       'Ping Bot',          'Cek response bot'],
  ['runtime',    'Runtime Bot',       'Uptime bot sejak terakhir restart'],
  ['speed',      'Speed Test',        'Tes kecepatan koneksi server'],
  ['ram',        'RAM Usage',         'Monitor penggunaan RAM'],
  ['cpu',        'CPU Info',          'Info CPU server'],
  ['uptime',     'Uptime Server',     'Waktu server berjalan'],
  ['myinfo',     'Info Diri',         'Info tentang dirimu'],
  ['botinfo',    'Info Bot',          'Informasi lengkap bot'],
  ['owner',      'Kontak Owner',      'Tampilkan kontak owner'],
  ['calc',       'Kalkulator',        'Hitung ekspresi matematika'],
  ['kalkul',     'Kalkulator Lanjut', 'Kalkulator ekspresi kompleks'],
  ['qr',         'QR Code',           'Buat QR code dari teks/URL'],
  ['short',      'Short URL',         'Persingkat URL panjang'],
  ['passgen',    'Password Gen',      'Buat password acak aman'],
  ['pinbuat',    'PIN Generator',     'Buat PIN 4/6/8 digit'],
  ['ip',         'IP Lookup',         'Info detail IP address'],
  ['myip',       'IP Saya',           'Cek IP publik server'],
  ['cuaca',      'Info Cuaca',        'Cuaca real-time suatu kota'],
  ['cuacahr',    'Prakiraan Cuaca',   'Prakiraan cuaca 7 hari'],
  ['gempa',      'Info Gempa',        'Gempa terbaru dari BMKG'],
  ['kurs',       'Kurs Mata Uang',    'Nilai tukar mata uang real-time'],
  ['kursid',     'Kurs IDR',          'Nilai tukar rupiah vs semua mata uang'],
  ['waktu',      'Waktu Kota',        'Waktu sekarang di kota mana pun'],
  ['kalender',   'Kalender',          'Kalender bulan dan tahun'],
  ['hari',       'Hari Ini',          'Info hari ini lengkap'],
  ['hitunghari', 'Hitung Hari',       'Hitung selisih hari antara dua tanggal'],
  ['umur',       'Hitung Umur',       'Hitung umur dari tanggal lahir'],
  ['zodiak',     'Zodiak',            'Cek zodiak dari tanggal lahir'],
  ['shio',       'Shio',              'Cek shio dari tahun lahir'],
  ['primbon',    'Primbon Jawa',      'Primbon Jawa berdasarkan tanggal lahir'],
  ['weton',      'Weton Jawa',        'Cek weton dari tanggal lahir'],
  ['bmi',        'Hitung BMI',        'Body Mass Index kamu'],
  ['kalori',     'Hitung Kalori',     'Estimasi kebutuhan kalori harian'],
  ['konversibb', 'Konversi Berat',    'Konversi satuan berat'],
  ['konversijrk','Konversi Jarak',    'Konversi satuan jarak'],
  ['konversisuhu','Konversi Suhu',    'Konversi Celsius/Fahrenheit/Kelvin'],
  ['konversivol','Konversi Volume',   'Konversi satuan volume'],
  ['konversiarea','Konversi Luas',    'Konversi satuan luas'],
  ['konversidata','Konversi Data',    'Konversi satuan data (KB/MB/GB)'],
  ['bilangan',   'Konversi Bilangan', 'Konversi bilangan (biner/oktal/hex)'],
  ['romawi',     'Angka Romawi',      'Konversi angka ke/dari romawi'],
  ['roman',      'Angka → Romawi',    'Ubah angka ke huruf romawi'],
  ['terbilang',  'Terbilang',         'Angka ke kata (terbilang Indonesia)'],
  ['katakata',   'Kata Tersembunyi',  'Cari kata tersembunyi dalam teks'],
  ['palindrom',  'Cek Palindrom',     'Cek apakah kata palindrom'],
  ['anagram',    'Anagram',           'Cek/buat anagram kata'],
  ['validasi',   'Validasi Input',    'Validasi email, URL, nomor'],
  ['emailcek',   'Cek Email',         'Cek apakah email valid'],
  ['urlcek',     'Cek URL',           'Cek apakah URL aktif/valid'],
  ['nocek',      'Cek Nomor WA',      'Cek apakah nomor ada di WA'],
  ['random',     'Angka Random',      'Generate angka acak dalam range'],
  ['pilih',      'Pilih Acak',        'Pilih satu dari beberapa pilihan'],
  ['koin',       'Lempar Koin',       'Heads or Tails'],
  ['dadu',       'Lempar Dadu',       'Lempar dadu 1-6'],
  ['dadux',      'Dadu Custom',       'Lempar N dadu sisi M'],
  ['uuid',       'Generate UUID',     'Buat UUID v4 unik'],
  ['nanoid',     'Generate NanoID',   'Buat ID pendek unik'],
  ['timestamp',  'Unix Timestamp',    'Konversi waktu ke Unix timestamp'],
  ['md5',        'Hash MD5',          'Buat hash MD5 dari teks'],
  ['sha1',       'Hash SHA1',         'Buat hash SHA1 dari teks'],
  ['sha256',     'Hash SHA256',       'Buat hash SHA256 dari teks'],
  ['morse',      'Kode Morse',        'Encode/decode kode Morse'],
  ['sandi',      'Sandi Substitusi',  'Encode teks dengan sandi substitusi'],
  ['caesar',     'Caesar Cipher',     'Encode/decode Caesar cipher'],
  ['vigenere',   'Vigenere Cipher',   'Encode teks dengan Vigenere cipher'],
  ['binarytext', 'Biner ↔ Teks',     'Konversi teks ke biner dan sebaliknya'],
  ['hextext',    'Hex ↔ Teks',       'Konversi teks ke hex'],
  ['asciiart',   'ASCII Art',         'Buat tulisan ASCII art dari teks'],
  ['qrwifi',     'QR WiFi',           'Buat QR untuk share password WiFi'],
  ['luhn',       'Validasi Luhn',     'Validasi nomor kartu kredit (Luhn)'],
  ['nik',        'Cek NIK',           'Decode info dari NIK KTP Indonesia'],
  ['plat',       'Info Plat Nomor',   'Cek asal daerah plat nomor kendaraan'],
  ['kodepos',    'Kode Pos',          'Cari kode pos wilayah Indonesia'],
  ['prov',       'Info Provinsi',     'Info provinsi-provinsi di Indonesia'],
  ['nomorhp',    'Format Nomor HP',   'Format dan validasi nomor HP Indonesia'],
  ['pbsnow',     'PhoneBook Search',  'Cari info dari nomor telepon'],
  ['colorpick',  'Color Info',        'Info warna dari kode hex/rgb'],
  ['colorname',  'Nama Warna',        'Nama warna dalam bahasa Indonesia'],
  ['gradientgen','Gradient Gen',      'Generate CSS gradient code'],
  ['fontstyle',  'Font Style',        'Ubah teks ke berbagai style unicode'],
  ['superscript','Superscript',       'Teks superscript ˢᵘᵖᵉʳˢᶜʳⁱᵖᵗ'],
  ['subscript',  'Subscript',         'Teks subscript ₛᵤᵦₛₓᵣᵢₚₜ'],
  ['smallcaps',  'Small Caps',        'Teks sᴍᴀʟʟ ᴄᴀᴘs'],
  ['bold',       'Bold Text',         'Teks 𝗯𝗼𝗹𝗱'],
  ['italic',     'Italic Text',       'Teks 𝘪𝘵𝘢𝘭𝘪𝘤'],
  ['strikethrough','Strikethrough',   'Teks s̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶'],
  ['bubbletxt',  'Bubble Text',       'Teks ⓑⓤⓑⓑⓛⓔ'],
  ['squaretxt',  'Square Text',       'Teks 🅂🅀🅄🄰🅁🄴'],
  ['mirror',     'Mirror Text',       'Teks ᴛxǝʇ ɹoɹɹᴉɯ'],
  ['updown',     'Upside Down',       'Teks dn ǝpᴉsdn'],
  ['zalgo',      'Zalgo Text',        'T̶̙͍e̴͚͠x̷͕͘t̵̬̑ Zalgo horror'],
  ['wabold',     'WhatsApp Bold',     'Buat teks *bold* WA'],
  ['waitalic',   'WhatsApp Italic',   'Buat teks _italic_ WA'],
  ['wmono',      'WA Monospace',      'Buat teks ```monospace``` WA'],
  ['kataacak',   'Kata Acak',         'Buat kata acak dari huruf'],
  ['namagen',    'Nama Generator',    'Generate nama acak Indonesia'],
  ['namagame',   'Nama Game',         'Generate nama keren untuk game'],
  ['namaarab',   'Nama Arab',         'Arti nama bahasa Arab'],
  ['namajawa',   'Nama Jawa',         'Arti nama bahasa Jawa'],
  ['namabarat',  'Nama Barat',        'Arti nama bahasa Barat/Latin'],
])

// ══════════════════════════════════════════
// 2. TRANSLATOR  (100 bahasa) ~100 fitur
// ══════════════════════════════════════════
const LANGS = [
  ['id','Indonesia'],['en','Inggris'],['ja','Jepang'],['ko','Korea'],['zh','Mandarin'],
  ['ar','Arab'],['fr','Prancis'],['de','Jerman'],['es','Spanyol'],['it','Italia'],
  ['pt','Portugis'],['ru','Rusia'],['hi','Hindi'],['th','Thailand'],['vi','Vietnam'],
  ['ms','Melayu'],['tr','Turki'],['nl','Belanda'],['pl','Polandia'],['sv','Swedia'],
  ['da','Denmark'],['fi','Finlandia'],['no','Norwegia'],['cs','Ceko'],['sk','Slovakia'],
  ['hu','Hongaria'],['ro','Rumania'],['bg','Bulgaria'],['hr','Kroasia'],['sr','Serbia'],
  ['uk','Ukraina'],['el','Yunani'],['he','Ibrani'],['fa','Persia/Farsi'],['ur','Urdu'],
  ['bn','Bengali'],['ta','Tamil'],['te','Telugu'],['ml','Malayalam'],['kn','Kannada'],
  ['gu','Gujarati'],['mr','Marathi'],['pa','Punjabi'],['si','Sinhala'],['my','Myanmar'],
  ['km','Khmer'],['lo','Laos'],['mn','Mongolia'],['ka','Georgia'],['hy','Armenia'],
  ['az','Azerbaijan'],['kk','Kazakh'],['uz','Uzbekistan'],['tk','Turkmenistan'],
  ['ky','Kyrgyz'],['tg','Tajik'],['be','Belarusia'],['lv','Latvia'],['lt','Lituania'],
  ['et','Estonia'],['lb','Luksemburg'],['mt','Malta'],['cy','Wales'],['ga','Irlandia'],
  ['eu','Basque'],['ca','Katalan'],['gl','Galicia'],['af','Afrikaans'],['sw','Swahili'],
  ['am','Amharik'],['ha','Hausa'],['ig','Igbo'],['yo','Yoruba'],['zu','Zulu'],
  ['xh','Xhosa'],['sn','Shona'],['so','Somalia'],['mg','Malagasi'],['rw','Kinyarwanda'],
  ['ny','Chichewa'],['st','Sesotho'],['tn','Tswana'],['ak','Akan'],['ee','Ewe'],
  ['jv','Jawa'],['su','Sunda'],['ceb','Cebuano'],['tl','Tagalog/Filipino'],
  ['ilo','Ilocano'],['hmn','Hmong'],['haw','Hawaii'],['sm','Samoa'],['to','Tonga'],
  ['fj','Fiji'],['mi','Maori'],['eo','Esperanto'],['la','Latin'],['fy','Frisian'],
  ['yi','Yiddish'],['ht','Haiti Creole'],['co','Korsika'],['br','Breton'],['oc','Oksitan'],
]
LANGS.forEach(([code, name]) => {
  f('translator', 'tr'+code, 'Translate → '+name, 'Terjemahkan teks ke bahasa '+name, 'translate', { lang:code })
})

// ══════════════════════════════════════════
// 3. AI & CHATBOT  ~100 fitur
// ══════════════════════════════════════════
batch('ai', [
  ['ai',        'AI Chat',           'Chat dengan AI berbasis LLM'],
  ['gpt',       'GPT Chat',          'Chat dengan GPT'],
  ['ask',       'Tanya AI',          'Tanya pertanyaan apapun ke AI'],
  ['imagine',   'AI Image Gen',      'Buat gambar dari deskripsi teks'],
  ['imagine2',  'AI Image (v2)',     'Generate gambar dengan model berbeda'],
  ['artgen',    'AI Art',            'Buat seni AI digital'],
  ['animeimg',  'Anime Image AI',    'Generate gambar anime style'],
  ['realisticimg','Foto Realistis',  'Generate foto realistis AI'],
  ['tts',       'Text to Speech',    'Ubah teks ke suara'],
  ['tts_id',    'TTS Indonesia',     'TTS dalam bahasa Indonesia'],
  ['tts_en',    'TTS English',       'TTS dalam bahasa Inggris'],
  ['tts_ja',    'TTS Jepang',        'TTS dalam bahasa Jepang'],
  ['tts_ko',    'TTS Korea',         'TTS dalam bahasa Korea'],
  ['tts_ar',    'TTS Arab',          'TTS dalam bahasa Arab'],
  ['summarize', 'Rangkum Teks',      'Rangkum teks panjang jadi poin'],
  ['parafrase', 'Parafrase',         'Tulis ulang teks dengan kata berbeda'],
  ['improve',   'Perbaiki Teks',     'Perbaiki tata bahasa dan gaya teks'],
  ['formal',    'Buat Formal',       'Ubah teks informal ke formal'],
  ['informal',  'Buat Santai',       'Ubah teks formal ke santai/casual'],
  ['email',     'Buat Email',        'Buat template email profesional'],
  ['cover',     'Cover Letter',      'Buat surat lamaran kerja AI'],
  ['cv',        'Review CV',         'Review dan tips perbaiki CV'],
  ['essay',     'Buat Esai',         'Buat esai tentang topik tertentu'],
  ['poem',      'Buat Puisi',        'Buat puisi dari tema/kata kunci'],
  ['cerpen',    'Buat Cerpen',       'Buat cerita pendek AI'],
  ['lirik',     'Buat Lirik Lagu',   'Buat lirik lagu dari topik'],
  ['caption',   'Buat Caption',      'Buat caption keren untuk foto/video'],
  ['hashtag',   'Buat Hashtag',      'Generate hashtag relevan untuk konten'],
  ['bio',       'Buat Bio Sosmed',   'Buat bio menarik untuk profil sosmed'],
  ['slogan',    'Buat Slogan',       'Buat slogan keren untuk brand'],
  ['namabrand', 'Nama Brand',        'Saran nama brand/bisnis'],
  ['copywrite', 'Copywriting',       'Buat copywriting persuasif'],
  ['ide',       'Brainstorm Ide',    'Generate ide kreatif untuk topik'],
  ['resume',    'Resume',            'Buat/review resume profesional'],
  ['surat',     'Buat Surat',        'Buat surat formal/informal'],
  ['review',    'Review Produk',     'Tulis review produk dari info'],
  ['roast',     'Roast (Fun)',       'AI roast seseorang dengan bercanda'],
  ['pujian',    'Pujian Random',     'AI buat pujian untuk seseorang'],
  ['gombal',    'Kata Gombal',       'Generate kata gombal kreatif'],
  ['pantun',    'Buat Pantun',       'Buat pantun dari tema'],
  ['teka',      'Teka-Teki',         'Generate teka-teki dengan jawabannya'],
  ['jokes',     'Jokes AI',          'Buat jokes/lelucon dari topik'],
  ['motivasi',  'Kata Motivasi',     'Quote motivasi AI generated'],
  ['saran',     'Minta Saran',       'Minta saran AI untuk masalah tertentu'],
  ['resep',     'Resep Masakan',     'Resep masakan dari bahan-bahan'],
  ['diet',      'Rencana Diet',      'Rencana diet/meal plan AI'],
  ['workout',   'Program Olahraga',  'Rencana workout dari AI'],
  ['itinerary', 'Rencana Perjalanan','Buat itinerary wisata AI'],
  ['bedakata',  'Beda Kata',         'Jelaskan perbedaan dua kata/konsep'],
  ['definisi',  'Definisi',          'Definisi lengkap suatu kata/konsep'],
  ['analogikan','Analogikan',        'Jelaskan konsep pakai analogi'],
  ['kodeai',    'Code AI',           'Generate kode dari deskripsi'],
  ['reviewkode','Review Kode',       'Review dan debug kode'],
  ['explaincode','Jelaskan Kode',    'Jelaskan apa yang dilakukan kode'],
  ['fixcode',   'Perbaiki Kode',     'Perbaiki bug/error dalam kode'],
])

// ══════════════════════════════════════════
// 4. IMAGE EDITING  ~200 fitur
// ══════════════════════════════════════════
batch('image', [
  ['blur',       'Blur',             'Blur gambar dengan level tertentu'],
  ['blur1','Blur Ringan','Blur level 1'],['blur5','Blur Sedang','Blur level 5'],['blur10','Blur Kuat','Blur level 10'],
  ['grayscale',  'Grayscale/BW',     'Ubah foto jadi hitam putih'],
  ['sepia',      'Sepia/Vintage',    'Efek foto vintage/sepia'],
  ['invert',     'Invert',           'Invert warna gambar'],
  ['brightness', 'Kecerahan',        'Atur kecerahan gambar'],
  ['contrast',   'Kontras',          'Atur kontras gambar'],
  ['saturation', 'Saturasi',         'Atur saturasi warna gambar'],
  ['hue',        'Hue Rotate',       'Putar hue warna gambar'],
  ['sharpen',    'Sharpen',          'Perjelas detail gambar'],
  ['soften',     'Soften',           'Perhalus/lembutkan gambar'],
  ['emboss',     'Emboss',           'Efek emboss/timbul'],
  ['edge',       'Edge Detect',      'Deteksi tepi gambar'],
  ['sketch',     'Efek Sketsa',      'Ubah foto jadi sketsa pensil'],
  ['cartoon',    'Efek Kartun',      'Ubah foto jadi kartun'],
  ['oil',        'Efek Cat Minyak',  'Efek lukisan cat minyak'],
  ['watercolor', 'Efek Cat Air',     'Efek lukisan cat air'],
  ['pixelate',   'Pixelate',         'Efek piksel kotak-kotak'],
  ['glitch',     'Efek Glitch',      'Efek glitch digital'],
  ['neon',       'Efek Neon',        'Efek lampu neon'],
  ['vhs',        'Efek VHS',         'Efek video VHS lama'],
  ['duotone',    'Duotone',          'Efek dua warna'],
  ['halftone',   'Halftone',         'Efek titik halftone'],
  ['fisheye',    'Fish Eye',         'Efek lensa fisheye'],
  ['tilt',       'Tilt Shift',       'Efek tilt-shift miniatir'],
  ['lomo',       'Lomo Effect',      'Efek kamera Lomo'],
  ['polaroid',   'Polaroid Frame',   'Beri frame polaroid'],
  ['filmstrip',  'Film Strip',       'Efek strip film'],
  ['vignette',   'Vignette',         'Tambahkan efek vignette'],
  ['grain',      'Film Grain',       'Tambahkan noise/grain film'],
  ['rainbow',    'Rainbow Filter',   'Overlay filter pelangi'],
  ['golden',     'Golden Hour',      'Filter golden hour'],
  ['cold',       'Cold Tone',        'Tone dingin/biru'],
  ['warm',       'Warm Tone',        'Tone hangat/kuning'],
  ['matrix',     'Matrix Green',     'Filter matrix hijau'],
  ['heat',       'Heatmap',          'Visualisasi heatmap warna'],
  ['crop',       'Crop',             'Potong gambar ke ukuran tertentu'],
  ['resize',     'Resize',           'Ubah ukuran gambar'],
  ['rotate',     'Rotate',           'Putar gambar sekian derajat'],
  ['flip',       'Flip/Mirror',      'Flip horizontal atau vertikal'],
  ['roundcorner','Round Corner',     'Beri sudut melengkung pada gambar'],
  ['circle',     'Crop Lingkaran',   'Crop gambar menjadi lingkaran'],
  ['square',     'Crop Kotak',       'Crop gambar menjadi kotak 1:1'],
  ['16to9',      'Crop 16:9',        'Crop gambar ke rasio 16:9'],
  ['compress',   'Kompres',          'Kompres ukuran file gambar'],
  ['enlarge',    'Perbesar',         'Perbesar gambar (upscale AI)'],
  ['watermark',  'Watermark',        'Tambahkan watermark teks ke gambar'],
  ['caption',    'Caption Gambar',   'Tambahkan teks caption di gambar'],
  ['meme',       'Buat Meme',        'Tambahkan teks atas/bawah ala meme'],
  ['overlay',    'Overlay Teks',     'Teks overlay dengan posisi bebas'],
  ['collage2',   'Kolase 2 Foto',    'Gabung 2 foto berdampingan'],
  ['collage4',   'Kolase 4 Foto',    'Gabung 4 foto dalam grid'],
  ['before_after','Before/After',    'Split view before-after'],
  ['palette',    'Color Palette',    'Ekstrak palet warna dari gambar'],
  ['dominant',   'Warna Dominan',    'Cari warna dominan gambar'],
  ['imginfo',    'Info Gambar',      'Metadata dan info gambar'],
  ['exif',       'EXIF Data',        'Baca data EXIF gambar'],
  ['nsfw_check', 'Cek NSFW',        'Cek apakah gambar mengandung konten 18+'],
  ['face_detect','Deteksi Wajah',    'Deteksi jumlah wajah dalam foto'],
  ['nude_blur',  'Blur Otomatis',    'Blur area sensitif otomatis'],
])

// ══════════════════════════════════════════
// 5. STICKER  ~100 fitur
// ══════════════════════════════════════════
batch('sticker', [
  ['s',          'Buat Stiker',      'Buat stiker dari gambar/video'],
  ['s2',         'Stiker (HD)',      'Buat stiker kualitas HD'],
  ['sgif',       'Stiker GIF',       'Buat stiker animasi dari GIF'],
  ['swebp',      'Stiker WebP',      'Buat stiker format WebP'],
  ['svid',       'Stiker Video',     'Buat stiker dari video pendek'],
  ['surl',       'Stiker dari URL',  'Buat stiker dari gambar online'],
  ['toimg',      'Stiker → Gambar',  'Konversi stiker ke PNG'],
  ['togif',      'Stiker → GIF',     'Konversi stiker animasi ke GIF'],
  ['stxt',       'Stiker Teks',      'Buat stiker dari teks'],
  ['semoji',     'Stiker Emoji',     'Buat stiker dari emoji besar'],
  ['scolor',     'Stiker Warna',     'Buat stiker warna solid'],
  ['sblur',      'Stiker Blur',      'Buat stiker dengan efek blur'],
  ['sround',     'Stiker Bulat',     'Buat stiker berbentuk lingkaran'],
  ['scrop',      'Crop Stiker',      'Crop stiker ke ukuran tertentu'],
  ['sresize',    'Resize Stiker',    'Ubah ukuran stiker'],
  ['sframe',     'Frame Stiker',     'Tambahkan frame ke stiker'],
  ['sborder',    'Border Stiker',    'Tambahkan border ke stiker'],
  ['sglow',      'Glow Stiker',      'Efek glow pada stiker'],
  ['sshadow',    'Shadow Stiker',    'Efek bayangan pada stiker'],
  ['sinvert',    'Invert Stiker',    'Invert warna stiker'],
  ['sgray',      'BW Stiker',        'Ubah stiker jadi hitam-putih'],
  ['ssepia',     'Sepia Stiker',     'Efek sepia pada stiker'],
  ['sblueprint', 'Blueprint',        'Efek blueprint/cyanotype'],
  ['swm',        'Watermark Stiker', 'Tambahkan watermark ke stiker'],
  ['spack',      'Info Pack',        'Lihat info pack stiker'],
  ['stealstk',   'Ambil Stiker',     'Simpan stiker ke koleksi'],
  ['kirimstk',   'Kirim Stiker',     'Kirim stiker dari koleksi'],
  ['daftarstk',  'Daftar Stiker',    'Lihat daftar stiker tersimpan'],
  ['emojimix1',  'Emoji Mix (1)',    'Mix emoji gaya 1'],
  ['emojimix2',  'Emoji Mix (2)',    'Mix emoji gaya 2'],
  ['stickerpack','Stiker Pack',      'Download pack stiker WhatsApp'],
])

// ══════════════════════════════════════════
// 6. DOWNLOADER  ~120 fitur
// ══════════════════════════════════════════
batch('downloader', [
  ['ytmp3',    'YouTube MP3',       'Download YouTube jadi audio MP3'],
  ['ytmp4',    'YouTube MP4',       'Download YouTube jadi video MP4'],
  ['ytmp4hd',  'YouTube MP4 HD',   'Download YouTube HD 720p'],
  ['ytmp4fhd', 'YouTube Full HD',  'Download YouTube Full HD 1080p'],
  ['ytthumb',  'YouTube Thumbnail','Download thumbnail YouTube'],
  ['ytsubtitle','YouTube Subtitles','Download subtitle YouTube'],
  ['ytinfo',   'YouTube Info',     'Info video YouTube'],
  ['ytsearch', 'YouTube Search',   'Cari video YouTube'],
  ['ytplaylist','YT Playlist DL',  'Download seluruh playlist YouTube'],
  ['ig',       'Instagram DL',     'Download foto/video Instagram'],
  ['igreels',  'IG Reels',         'Download Instagram Reels'],
  ['igstory',  'IG Story',         'Download Instagram Story'],
  ['ighighlight','IG Highlight',   'Download Instagram Highlight'],
  ['igprofilepic','IG Profile Pic','Download foto profil Instagram'],
  ['tt',       'TikTok DL',        'Download TikTok tanpa watermark'],
  ['ttmlive',  'TikTok Live',      'Download TikTok Live recording'],
  ['ttslide',  'TikTok Slideshow', 'Download TikTok slideshow foto'],
  ['ttprofile','TikTok Profile',   'Download foto profil TikTok'],
  ['fb',       'Facebook Video',   'Download video Facebook'],
  ['fbstory',  'FB Story',         'Download Facebook Story'],
  ['fbphoto',  'FB Photo',         'Download foto dari Facebook'],
  ['twitter',  'Twitter/X DL',     'Download video/gif Twitter/X'],
  ['threads',  'Threads DL',       'Download konten Threads'],
  ['snapchat', 'Snapchat DL',      'Download story Snapchat'],
  ['pinterest','Pinterest DL',     'Download gambar Pinterest'],
  ['tumblr',   'Tumblr DL',        'Download konten Tumblr'],
  ['reddit',   'Reddit DL',        'Download video/gif Reddit'],
  ['twitch',   'Twitch Clip',      'Download clip Twitch'],
  ['youtube',  'YouTube Search DL','Cari dan download YouTube sekaligus'],
  ['spotify',  'Spotify DL',       'Download lagu Spotify (audio)'],
  ['spotifypl','Spotify Playlist', 'Download playlist Spotify'],
  ['deezer',   'Deezer DL',        'Download lagu dari Deezer'],
  ['soundcloud','SoundCloud DL',   'Download dari SoundCloud'],
  ['applemusic','Apple Music DL',  'Download dari Apple Music'],
  ['joox',     'JOOX DL',          'Download lagu dari JOOX'],
  ['resso',    'Resso DL',         'Download lagu dari Resso'],
  ['capcut',   'CapCut DL',        'Download video dari CapCut'],
  ['kwai',     'Kwai DL',          'Download video dari Kwai'],
  ['likee',    'Likee DL',         'Download video dari Likee'],
  ['bigo',     'BIGO Live',        'Download clip BIGO Live'],
  ['vimeo',    'Vimeo DL',         'Download video dari Vimeo'],
  ['dailymotion','Dailymotion DL', 'Download dari Dailymotion'],
  ['gdrive',   'Google Drive DL',  'Download dari Google Drive (publik)'],
  ['mediafire','Mediafire DL',     'Download dari Mediafire'],
  ['zippyshare','ZippyShare DL',   'Download dari ZippyShare'],
  ['mega',     'MEGA DL',          'Download dari MEGA'],
  ['dropbox',  'Dropbox DL',       'Download dari Dropbox'],
  ['onedrive', 'OneDrive DL',      'Download dari OneDrive'],
  ['terabox',  'TeraBox DL',       'Download dari TeraBox'],
  ['apk',      'APK Search',       'Cari dan info APK Android'],
  ['apkpure',  'APKPure DL',       'Download APK dari APKPure'],
  ['playstore','Play Store Info',  'Info aplikasi dari Google Play Store'],
  ['appstore', 'App Store Info',   'Info aplikasi dari Apple App Store'],
  ['wallpaper','Wallpaper DL',     'Download wallpaper berkualitas tinggi'],
  ['unsplash', 'Unsplash Photo',   'Download foto gratis dari Unsplash'],
  ['pixabay',  'Pixabay DL',       'Download gambar dari Pixabay'],
  ['pexels',   'Pexels DL',        'Download foto dari Pexels'],
  ['giftenor', 'Tenor GIF',        'Download GIF dari Tenor'],
  ['giphygif', 'GIPHY GIF',        'Download GIF dari GIPHY'],
  ['ebook',    'E-Book DL',        'Cari dan download e-book'],
  ['pdf',      'PDF DL',           'Download PDF dari URL'],
  ['subtitle', 'Subtitle DL',      'Download subtitle dari OpenSubtitles'],
  ['manga',    'Manga DL',         'Download chapter manga'],
  ['anime_ep', 'Anime Episode',    'Download episode anime (info)'],
  ['movie',    'Movie DL',         'Info dan link download film'],
  ['news_img', 'News Image',       'Download gambar berita'],
  ['icon',     'App Icon',         'Download ikon aplikasi'],
  ['favicon',  'Favicon',          'Download favicon dari website'],
  ['ssweb',    'Screenshot Web',   'Screenshot halaman website'],
  ['ssmobile', 'SS Mobile View',   'Screenshot tampilan mobile website'],
])

// ══════════════════════════════════════════
// 7. GAMES  ~400 fitur
// ══════════════════════════════════════════
batch('game', [
  ['truth',     'Truth',            'Pertanyaan truth acak'],
  ['dare',      'Dare',             'Tantangan dare acak'],
  ['trutdare',  'Truth or Dare',    'Main truth or dare bersama'],
  ['8ball',     'Magic 8-Ball',     'Pertanyaan ke magic 8 ball'],
  ['siapakah',  'Siapakah?',        'Siapakah di grup ini yang...'],
  ['apakah',    'Apakah Kamu?',     'Apakah kamu...?'],
  ['nyebut',    'Nyebut',           'Taruhan siapa yang nyebut duluan'],
  ['tebakkata', 'Tebak Kata',       'Tebak kata dari hint'],
  ['tebakangka','Tebak Angka',      'Tebak angka yang disembunyikan bot'],
  ['tebakbendera','Tebak Bendera',  'Tebak nama negara dari bendera emoji'],
  ['tebaklogo', 'Tebak Logo',       'Tebak nama brand dari logo (blur)'],
  ['tebakfilm', 'Tebak Film',       'Tebak judul film dari hint'],
  ['tebakartis','Tebak Artis',      'Tebak nama artis dari hint'],
  ['tebaklagu', 'Tebak Lagu',       'Tebak judul lagu dari lirik petikan'],
  ['tebakcharacter','Tebak Karakter','Tebak karakter dari deskripsi'],
  ['tebakbuah', 'Tebak Buah',       'Tebak buah dari deskripsi'],
  ['tebakbinatang','Tebak Hewan',   'Tebak hewan dari deskripsi'],
  ['tebakprovinsi','Tebak Provinsi','Tebak provinsi dari clue'],
  ['tebaknegara','Tebak Negara',    'Tebak negara dari clue'],
  ['tebakibu',  'Tebak Ibu Kota',   'Tebak ibu kota negara'],
  ['tebakmata', 'Tebak Mata Uang',  'Tebak mata uang dari nama negara'],
  ['tebakpresiden','Tebak Presiden','Tebak presiden/pemimpin negara'],
  ['tebakprofesi','Tebak Profesi',  'Tebak profesi dari deskripsi'],
  ['quiz',      'Quiz Umum',        'Kuis pengetahuan umum'],
  ['quizipa',   'Quiz IPA',         'Kuis ilmu pengetahuan alam'],
  ['quizips',   'Quiz IPS',         'Kuis ilmu pengetahuan sosial'],
  ['quizmath',  'Quiz Matematika',  'Soal matematika acak'],
  ['quizbahasa','Quiz B. Indonesia','Kuis Bahasa Indonesia'],
  ['quizinggris','Quiz B. Inggris', 'Kuis Bahasa Inggris'],
  ['quizgeografi','Quiz Geografi',  'Kuis geografi dunia'],
  ['quizsejarah','Quiz Sejarah',    'Kuis sejarah Indonesia dan dunia'],
  ['quizagama', 'Quiz Agama',       'Kuis pengetahuan agama'],
  ['quizpop',   'Quiz Pop Culture', 'Kuis budaya populer'],
  ['quizmovie', 'Quiz Film',        'Kuis seputar film'],
  ['quizmusic', 'Quiz Musik',       'Kuis seputar musik'],
  ['quizanime', 'Quiz Anime',       'Kuis seputar anime dan manga'],
  ['quizgame',  'Quiz Game',        'Kuis seputar video game'],
  ['quizsport', 'Quiz Olahraga',    'Kuis seputar olahraga'],
  ['quiztech',  'Quiz Teknologi',   'Kuis seputar teknologi'],
  ['suit',      'Suit (RPS)',       'Rock Paper Scissors vs bot'],
  ['suitgroup', 'Suit Tournament',  'Turnamen suit di grup'],
  ['flip',      'Lempar Koin',      'Heads or tails'],
  ['dadud6',    'Dadu D6',          'Lempar dadu 6 sisi'],
  ['dadud12',   'Dadu D12',         'Lempar dadu 12 sisi'],
  ['dadud20',   'Dadu D20',         'Lempar dadu 20 sisi (D&D)'],
  ['lotere',    'Lotere',           'Generate nomor lotere beruntung'],
  ['lucky',     'Nomor Keberuntungan','Generate angka keberuntungan hari ini'],
  ['tarotcard', 'Tarot Card',       'Cabut kartu tarot dan maknanya'],
  ['kartupoker','Kartu Poker',      'Cabut kartu poker acak'],
  ['spin',      'Spin Wheel',       'Spin wheel pilihan'],
  ['akukarakter','Aku Karakter',    'Kamu termasuk karakter mana?'],
  ['sifatmu',   'Sifatmu Hari Ini', 'Sifat random kamu hari ini'],
  ['nasibmu',   'Nasibmu',          'Nasib random kamu hari ini'],
  ['jodohmu',   'Jodohmu',          'Siapa jodohmu di grup?'],
  ['kelucuanmu','Kelucuanmu',       'Seberapa lucu kamu?'],
  ['kecerdasanmu','Kecerdasanmu',   'Seberapa cerdas kamu hari ini?'],
  ['kebaikumu', 'Kebaikanmu',       'Seberapa baik hati kamu?'],
  ['mabar',     'Mabar Finder',     'Cari teman main bareng game'],
  ['rank',      'Cek Rank',         'Cek rank kamu di leaderboard game'],
  ['wordchain', 'Word Chain',       'Rantai kata (kata terakhir → mulai baru)'],
  ['passcatatan','Password Notes',  'Game asal tebak password notes'],
  ['bingo',     'Bingo',           'Main bingo di grup'],
  ['caklontong','Cak Lontong',      'Game pertanyaan mudah, jawaban sulit'],
  ['sambunglirik','Sambung Lirik',  'Sambung lirik lagu bersama'],
  ['sambungkalimat','Sambung Kalimat','Sambung kalimat bersama'],
  ['matematikacepat','Mtk Cepat',   'Jawab soal matematika secepat mungkin'],
  ['ketikacepat','Ketik Cepat',     'Race ketik kalimat tercepat'],
  ['emojirace', 'Emoji Race',       'Tebak arti rangkaian emoji'],
  ['akronim',   'Akronim Game',     'Buat kepanjangan akronim lucu'],
])

// ══════════════════════════════════════════
// 8. RPG SYSTEM  ~200 fitur
// ══════════════════════════════════════════
batch('rpg', [
  ['profil',    'Profil RPG',       'Lihat profil karakter RPG'],
  ['battle',    'Battle PvP',       'Bertarung melawan pemain lain'],
  ['attack',    'Serang',           'Serang musuh dalam battle'],
  ['defend',    'Bertahan',         'Bertahan dari serangan'],
  ['skill',     'Gunakan Skill',    'Gunakan skill khusus karakter'],
  ['heal',      'Heal',             'Pulihkan HP dengan item'],
  ['lvlup',     'Level Up',         'Naikkan level manual'],
  ['stat',      'Lihat Stat',       'Lihat semua statistik karakter'],
  ['inventory', 'Inventory',        'Lihat item di tas'],
  ['equip',     'Equip Item',       'Pasang senjata/armor'],
  ['unequip',   'Unequip',          'Lepaskan senjata/armor'],
  ['drop',      'Buang Item',       'Buang item dari inventory'],
  ['shop',      'Toko RPG',         'Buka toko item RPG'],
  ['buy',       'Beli Item',        'Beli item dari toko'],
  ['sell',      'Jual Item',        'Jual item ke toko'],
  ['craft',     'Craft Item',       'Buat item dari material'],
  ['gather',    'Kumpul Material',  'Kumpulkan material dari alam'],
  ['mine',      'Tambang',          'Tambang mineral berharga'],
  ['fish',      'Memancing',        'Pergi memancing untuk item'],
  ['hunt',      'Berburu',          'Berburu hewan untuk exp & item'],
  ['farm',      'Bertani',          'Bertani untuk mendapatkan bahan'],
  ['dungeon',   'Masuk Dungeon',    'Masuki dungeon dan lawan boss'],
  ['raid',      'Raid',             'Raid dungeon sulit'],
  ['boss',      'Lawan Boss',       'Tantang boss dungeon'],
  ['quest',     'Quest',            'Lihat dan ambil quest'],
  ['dailyquest','Daily Quest',      'Quest harian untuk reward'],
  ['guild',     'Guild',            'Lihat info guild'],
  ['guildcreate','Buat Guild',      'Buat guild baru'],
  ['guildjoin', 'Gabung Guild',     'Gabung ke guild'],
  ['guildleave','Keluar Guild',     'Keluar dari guild'],
  ['guildwar',  'Guild War',        'Perang antar guild'],
  ['guildshop', 'Guild Shop',       'Toko eksklusif anggota guild'],
  ['pet',       'Peliharaan',       'Lihat dan rawat hewan peliharaan'],
  ['petbuy',    'Beli Peliharaan',  'Beli hewan peliharaan'],
  ['petfeed',   'Kasih Makan Pet',  'Kasih makan hewan peliharaan'],
  ['petlvl',    'Level Pet',        'Naikkan level peliharaan'],
  ['mount',     'Kendaraan',        'Lihat kendaraan RPG'],
  ['house',     'Rumah RPG',        'Beli dan kelola rumah di dunia RPG'],
  ['bank',      'Bank RPG',         'Simpan/tarik gold di bank'],
  ['transfer',  'Transfer Gold',    'Transfer gold ke pemain lain'],
  ['leaderboard','Leaderboard',     'Ranking pemain RPG server'],
  ['lb_level',  'LB Level',         'Ranking berdasarkan level'],
  ['lb_gold',   'LB Gold',          'Ranking berdasarkan kekayaan'],
  ['lb_wins',   'LB Wins',          'Ranking berdasarkan kemenangan'],
  ['lb_guild',  'LB Guild',         'Ranking guild terkuat'],
  ['class',     'Kelas Karakter',   'Pilih/lihat kelas karakter'],
  ['class_warrior','Warrior',       'Kelas prajurit, HP dan ATK tinggi'],
  ['class_mage','Mage',             'Kelas penyihir, skill kuat'],
  ['class_archer','Archer',         'Kelas pemanah, AGI tinggi'],
  ['class_thief','Thief',           'Kelas pencuri, kritis tinggi'],
  ['class_healer','Healer',         'Kelas healer, support teman'],
  ['class_tank','Tank',             'Kelas tank, DEF sangat tinggi'],
  ['reset',     'Reset Karakter',   'Reset karakter dari awal'],
  ['rename',    'Ganti Nama Char',  'Ganti nama karakter RPG'],
  ['story',     'Cerita RPG',       'Baca lore/cerita dunia RPG'],
  ['world',     'Peta Dunia',       'Lihat peta dunia RPG'],
  ['travel',    'Pergi ke Area',    'Pindah ke area lain'],
  ['area',      'Info Area',        'Info area/zona saat ini'],
  ['market',    'Pasar',            'Beli jual item antar pemain'],
  ['auction',   'Lelang',           'Lelang item rare ke pemain lain'],
  ['lottery_rpg','Lotere RPG',      'Beli tiket lotere untuk hadiah rare'],
  ['event',     'Event RPG',        'Event khusus terbatas waktu'],
  ['daily',     'Daily Reward',     'Klaim reward harian'],
  ['weekly',    'Weekly Reward',    'Klaim reward mingguan'],
  ['streak',    'Streak Login',     'Bonus streak login berturut-turut'],
  ['achievement','Pencapaian',      'Lihat achievement yang sudah diraih'],
  ['title',     'Gelar',            'Lihat dan pakai gelar karakter'],
  ['badge',     'Lencana',          'Koleksi lencana pencapaian'],
  ['skill_tree','Skill Tree',       'Lihat pohon skill karakter'],
  ['skillpoint','Skill Points',     'Lihat dan alokasi skill point'],
  ['power',     'Power Level',      'Hitung power level total karakter'],
  ['recover',   'Recover HP',       'Pulihkan HP secara manual'],
  ['revive',    'Revive',           'Bangkit kembali setelah kalah battle'],
  ['summon',    'Summon',           'Summon karakter/item dari gacha'],
  ['gacha',     'Gacha',            'Main gacha untuk item langka'],
  ['banner',    'Banner Gacha',     'Lihat banner gacha aktif'],
  ['pity',      'Pity Counter',     'Lihat pity counter gacha'],
  ['material',  'Material',         'Lihat daftar material crafting'],
  ['recipe',    'Resep Craft',      'Lihat resep pembuatan item'],
  ['storage',   'Gudang',           'Gudang penyimpanan item ekstra'],
  ['collection','Koleksi',          'Lihat koleksi item langka'],
])

// ══════════════════════════════════════════
// 9. ANIME & MANGA  ~300 fitur
// ══════════════════════════════════════════
const ANIME_SERIES = [
  'naruto','onepiece','bleach','dragonball','demonslayer','attackontitan',
  'mha','fullmetalalchemist','swordartonline','rezero','overlord','konosuba',
  'tensei','spiritedaway','totoro','princessmononoke','howlsmoving',
  'deathnote','codegeass','steinsgate','evangelion','cowboybebop','jojo',
  'hunterxhunter','gintama','fairytail','blackclover','bluelock','chainsaw',
  'spy_x_family','vinlandSaga','tokyoghoul','darlingfranxx','made_abyss',
  'goblinslayer','shieldHero','mushokuTensei','slime','dragonball_super',
  'boruto','shippuden','sagas','akame','noGameNoLife','log_horizon',
  'accelworld','isit_wrong','danmachi','mondaiji','irregular_academy',
  'nisekoi','toradora','clannad','anohana','yourname','weathering',
  'silent_voice','5cm','maquia','liz_bluebird','okko_inn','penguin_highway',
  'wolf_children','summer_wars','belle','mirai','onoda','yuri_ice',
  'hinomaru','diamonds_ace','major','slam_dunk','haikyuu','kuroko',
  'prince_tennis','captain_tsubasa','gegege','doraemon','crayon','pokemon',
  'digimon','beyblade','cardcaptor','sailormoon','precure','yugioh',
  'dragonballz','dragonballgt','robotics_notes','psychopass','aldnoah',
  'gurrenlagann','tengen_toppa','ttgl_movies','kill_la_kill','trigger',
]
ANIME_SERIES.forEach(a => {
  f('anime', 'anime_'+a, 'Info: '+a.replace(/_/g,' '), 'Informasi lengkap tentang anime '+a.replace(/_/g,' '), 'anime_info')
})
const ANIME_CMDS = [
  ['airing',    'Anime Airing',     'Anime yang sedang tayang sekarang'],
  ['topanime',  'Top Anime',        'Daftar top anime sepanjang masa'],
  ['recanime',  'Rekomendasi Anime','Rekomendasi anime berdasarkan genre'],
  ['animeschedule','Jadwal Anime',  'Jadwal tayang anime per hari'],
  ['animetag',  'Cari by Tag',      'Cari anime berdasarkan tag/genre'],
  ['mangainfo', 'Info Manga',       'Informasi detail manga'],
  ['mangachapter','Chapter Manga',  'Info chapter terbaru manga'],
  ['topmanGA',  'Top Manga',        'Top manga terpopuler'],
  ['animechar', 'Karakter Anime',   'Info karakter anime'],
  ['voiceactor','Voice Actor',      'Info voice actor anime'],
  ['anistudio', 'Studio Anime',     'Info studio animasi'],
  ['aniranking','Ranking Anime',    'Ranking anime berdasarkan skor'],
  ['anigenre',  'Genre Anime',      'Daftar anime berdasarkan genre'],
  ['anidub',    'Anime Dubbed',     'Cari anime yang ada dubnya'],
  ['aniseason', 'Musim Anime',      'Anime per musim (spring/summer/fall/winter)'],
  ['aniquote',  'Quote Anime',      'Quote keren dari anime'],
  ['anifact',   'Fakta Anime',      'Fakta menarik dunia anime'],
  ['aniimage',  'Gambar Anime',     'Gambar karakter anime acak'],
  ['neko',      'Neko Image',       'Gambar neko/kucing anime acak'],
  ['waifu',     'Waifu Random',     'Gambar waifu anime acak'],
  ['husbando',  'Husbando Random',  'Gambar husbando anime acak'],
  ['animeme',   'Anime Meme',       'Meme anime lucu'],
  ['anireact',  'Anime Reaction',   'GIF reaksi anime'],
  ['anihug',    'Anime Hug',        'GIF pelukan anime'],
  ['anikiss',   'Anime Kiss',       'GIF ciuman anime'],
  ['anipat',    'Anime Pat',        'GIF mengelus kepala anime'],
  ['aniwave',   'Anime Wave',       'GIF melambaikan tangan anime'],
  ['anilaugh',  'Anime Laugh',      'GIF tertawa anime'],
  ['anicry',    'Anime Cry',        'GIF menangis anime'],
  ['aniblush',  'Anime Blush',      'GIF malu/blush anime'],
  ['anislap',   'Anime Slap',       'GIF menampar anime'],
  ['anikick',   'Anime Kick',       'GIF menendang anime'],
  ['anipoke',   'Anime Poke',       'GIF colak anime'],
  ['anibite',   'Anime Bite',       'GIF gigit anime'],
  ['anibonk',   'Anime Bonk',       'GIF bonk anime'],
  ['anisus',    'Anime Sus',        'GIF sus/mencurigakan anime'],
  ['anidance',  'Anime Dance',      'GIF dance anime'],
  ['anisalute', 'Anime Salute',     'GIF hormat anime'],
  ['anismile',  'Anime Smile',      'GIF senyum anime'],
  ['aniwink',   'Anime Wink',       'GIF kedip mata anime'],
  ['aniconfuse','Anime Confused',   'GIF bingung anime'],
]
batch('anime', ANIME_CMDS)

// ══════════════════════════════════════════
// 10. FUN & RANDOM  ~300 fitur
// ══════════════════════════════════════════
batch('fun', [
  ['joke',      'Jokes Indonesia',  'Jokes lucu bahasa Indonesia'],
  ['jokeen',    'Jokes English',    'Jokes lucu bahasa Inggris'],
  ['jokesdark', 'Dark Jokes',       'Dark humor jokes (awas)'],
  ['jokesdad',  'Dad Jokes',        'Jokes garing ala Bapak-bapak'],
  ['jokes_it',  'IT Jokes',         'Jokes dunia programmer/IT'],
  ['quotes',    'Quotes Motivasi',  'Quote motivasi tokoh dunia'],
  ['quotelove', 'Quotes Cinta',     'Quote cinta romantis'],
  ['quotefun',  'Quotes Lucu',      'Quote lucu dan menghibur'],
  ['quotephilo','Quotes Filsafat',  'Quote filsafat mendalam'],
  ['quotelife', 'Quotes Kehidupan', 'Quote tentang kehidupan'],
  ['quoteinspire','Quotes Inspirasi','Quote inspirational'],
  ['quotesuccess','Quotes Sukses',  'Quote tentang kesuksesan'],
  ['quoteislam','Quotes Islam',     'Quote islami dari ulama'],
  ['quotekristen','Quotes Kristen', 'Quote kristen dan alkitab'],
  ['quotesaing','Saing Quote',      'Quote yang memotivasi saingan'],
  ['fakta',     'Fakta Random',     'Fakta acak menarik'],
  ['faktaid',   'Fakta Indonesia',  'Fakta unik tentang Indonesia'],
  ['faktadunia','Fakta Dunia',      'Fakta menarik tentang dunia'],
  ['faktailmu', 'Fakta Sains',      'Fakta ilmu pengetahuan'],
  ['faktaalam', 'Fakta Alam',       'Fakta tentang alam dan lingkungan'],
  ['faktahewan','Fakta Hewan',      'Fakta unik tentang hewan'],
  ['faktamanusia','Fakta Manusia',  'Fakta tubuh dan psikologi manusia'],
  ['faktamakanan','Fakta Makanan',  'Fakta unik tentang makanan'],
  ['faktasejarah','Fakta Sejarah',  'Fakta sejarah yang mengejutkan'],
  ['faktatech', 'Fakta Teknologi',  'Fakta menarik dunia teknologi'],
  ['faktaspace','Fakta Luar Angkasa','Fakta tentang luar angkasa'],
  ['faktaolahraga','Fakta Olahraga','Fakta unik dunia olahraga'],
  ['faktafilm', 'Fakta Film',       'Fakta behind the scenes film'],
  ['faktamusik','Fakta Musik',      'Fakta menarik dunia musik'],
  ['namahewan', 'Nama Hewan',       'Fakta & info hewan tertentu'],
  ['namatanaman','Nama Tanaman',    'Fakta & info tanaman tertentu'],
  ['warna',     'Info Warna',       'Psikologi dan makna warna'],
  ['horoscope', 'Horoskop Hari Ini','Horoskop 12 zodiak hari ini'],
  ['ramalan',   'Ramalan',          'Ramalan acak (hiburan)'],
  ['keberuntungan','Keberuntungan', 'Cek keberuntungan hari ini'],
  ['bintang',   'Bintang Zodiak',   'Cek bintang zodiak sesuai tanggal'],
  ['shiocek',   'Cek Shio',         'Cek shio dari tahun lahir'],
  ['personality','Tes Kepribadian', 'Tes kepribadian singkat (fun)'],
  ['mbti',      'MBTI Check',       'Cek tipe MBTI sesuai tanggal/input'],
  ['aesthetictype','Aesthetic Type','Cek aesthetic type kamu'],
  ['elementtype','Element Type',    'Kamu tipe elemen apa (api/air/dll)'],
  ['seasontype','Season Type',      'Kamu tipe musim apa'],
  ['animaltype','Hewan Kamu',       'Kamu cocok jadi hewan apa'],
  ['colortype', 'Warna Kamu',       'Warna yang cocok untuk kamu'],
  ['vibecheck', 'Vibe Check',       'Cek vibe kamu hari ini'],
  ['energylevel','Energy Level',    'Level energi kamu hari ini'],
  ['moodtoday', 'Mood Hari Ini',    'Mood random kamu hari ini'],
  ['luckymeal', 'Makanan Beruntung','Makanan keberuntungan harimu'],
  ['luckycolor','Warna Beruntung',  'Warna keberuntungan harimu'],
  ['luckynumber','Angka Beruntung', 'Angka keberuntungan harimu'],
  ['ucapanultah','Ucapan Ultah',    'Buat ucapan ulang tahun custom'],
  ['ucaplebaranid','Ucapan Lebaran','Template ucapan Idul Fitri'],
  ['ucapnataru','Ucapan Nataru',    'Template ucapan Natal & Tahun Baru'],
  ['ucapannikkah','Ucapan Nikah',   'Template ucapan pernikahan'],
  ['ucapanwisuda','Ucapan Wisuda',  'Template ucapan wisuda'],
  ['ucapanlulusan','Ucapan Lulus',  'Template ucapan kelulusan'],
  ['ucapanpromosi','Ucapan Promo',  'Template ucapan promosi jabatan'],
  ['ucapansakit','Ucapan Sakit',    'Doakan orang yang sakit'],
  ['ucapanduka', 'Ucapan Duka',     'Template ucapan belasungkawa'],
  ['ucapanbaru', 'Selamat Datang',  'Template ucapan sambutan'],
  ['meme',      'Random Meme',      'Meme random dari internet'],
  ['meme_id',   'Meme Indonesia',   'Meme Indonesia terpopuler'],
  ['meme_sponge','Spongebob Meme',  'Generate meme Spongebob'],
  ['meme_drake', 'Drake Meme',      'Generate meme Drake'],
  ['meme_always','Always Has Been', 'Generate meme astronaut'],
  ['meme_distracted','Distracted BF','Generate meme distracted BF'],
  ['meme_this_is_fine','This Is Fine','Generate meme anjing api'],
  ['meme_change_mind','Change Mind', 'Generate meme change my mind'],
  ['meme_uno',  'UNO Reverse',      'Generate meme UNO reverse'],
  ['meme_panik','Panik Kalm',       'Generate meme Panik/Kalm/Panik'],
  ['meme_giga', 'Gigachad',         'Generate meme Gigachad'],
  ['meme_npc',  'NPC Meme',         'Generate meme NPC'],
  ['gifhug',    'GIF Pelukan',      'GIF pelukan random'],
  ['giflaugh',  'GIF Ketawa',       'GIF ketawa random'],
  ['gifcry',    'GIF Nangis',       'GIF nangis random'],
  ['gifwave',   'GIF Lambaian',     'GIF melambaikan tangan'],
  ['gifthumbsup','GIF Jempol',      'GIF thumbs up'],
  ['gifapplause','GIF Tepuk Tangan','GIF tepuk tangan'],
  ['gifconfuse','GIF Bingung',      'GIF bingung/confused'],
  ['gifdance',  'GIF Dance',        'GIF dance random'],
  ['gifparty',  'GIF Party',        'GIF party/perayaan'],
  ['giffacepalm','GIF Facepalm',    'GIF facepalm'],
])

// ══════════════════════════════════════════
// 11. GROUP ADMIN  ~150 fitur
// ══════════════════════════════════════════
batch('group', [
  ['kick',      'Kick Member',      'Keluarkan member dari grup'],
  ['kickall',   'Kick Semua',       'Kick semua member kecuali admin'],
  ['add',       'Tambah Member',    'Tambahkan member ke grup'],
  ['promote',   'Promote Admin',    'Jadikan member sebagai admin'],
  ['demote',    'Demote Admin',     'Turunkan admin jadi member'],
  ['hidetag',   'Hidetag All',      'Tag semua member tanpa notif'],
  ['tagadmin',  'Tag Admin',        'Tag semua admin grup'],
  ['link',      'Group Link',       'Ambil link undangan grup'],
  ['revoke',    'Revoke Link',      'Reset link undangan grup'],
  ['setname',   'Set Nama Grup',    'Ubah nama grup'],
  ['setdesc',   'Set Deskripsi',    'Ubah deskripsi grup'],
  ['seticon',   'Set Icon Grup',    'Ubah icon/foto profil grup'],
  ['mute',      'Kunci Grup',       'Kunci grup (hanya admin yang bisa kirim)'],
  ['unmute',    'Buka Kunci',       'Buka kunci grup'],
  ['welcome',   'Welcome Message',  'Toggle pesan sambutan member baru'],
  ['setwelcome','Set Welcome Msg',  'Atur isi pesan sambutan'],
  ['welcome_img','Welcome Image',   'Sambut member baru dengan gambar'],
  ['goodbye',   'Goodbye Message',  'Toggle pesan perpisahan member keluar'],
  ['antilink',  'Anti Link',        'Toggle filter link otomatis'],
  ['antinsfw',  'Anti NSFW',        'Toggle filter gambar NSFW otomatis'],
  ['antispam',  'Anti Spam',        'Toggle perlindungan spam pesan'],
  ['antiflood', 'Anti Flood',       'Toggle perlindungan banjir pesan'],
  ['antibot',   'Anti Bot',         'Kick bot lain yang masuk grup'],
  ['antistiker','Anti Stiker',      'Toggle larangan kirim stiker'],
  ['antivoice', 'Anti Voice Note',  'Toggle larangan kirim voice note'],
  ['antivideo', 'Anti Video',       'Toggle larangan kirim video'],
  ['antidoc',   'Anti Dokumen',     'Toggle larangan kirim dokumen'],
  ['anticontact','Anti Kontak',     'Toggle larangan kirim kontak'],
  ['antiloc',   'Anti Lokasi',      'Toggle larangan kirim lokasi'],
  ['antifb',    'Anti FB Link',     'Blokir link Facebook'],
  ['antiig',    'Anti IG Link',     'Blokir link Instagram'],
  ['antitt',    'Anti TikTok',      'Blokir link TikTok'],
  ['antiyoutube','Anti YouTube',    'Blokir link YouTube'],
  ['antitwitter','Anti Twitter/X',  'Blokir link Twitter/X'],
  ['antibadword','Anti Kata Kasar', 'Filter kata-kata tidak pantas'],
  ['badwordlist','Daftar Bad Words','Lihat/tambah daftar bad words'],
  ['addword',   'Tambah Bad Word',  'Tambah kata ke filter'],
  ['delword',   'Hapus Bad Word',   'Hapus kata dari filter'],
  ['groupinfo', 'Info Grup',        'Info lengkap grup saat ini'],
  ['listgroup', 'List Grup',        'Daftar semua grup yang diikuti bot'],
  ['groupstat', 'Statistik Grup',   'Statistik aktivitas grup'],
  ['mostactive','Paling Aktif',     'Member paling aktif di grup'],
  ['leastactive','Paling Pasif',    'Member paling pasif di grup'],
  ['msgcount',  'Hitung Pesan',     'Hitung total pesan per member'],
  ['adminlist', 'Daftar Admin',     'Lihat semua admin grup'],
  ['memberlist','Daftar Member',    'Lihat semua member grup'],
  ['membercount','Jumlah Member',   'Hitung total member grup'],
  ['kicknonact','Kick Tidak Aktif', 'Kick member yang tidak aktif'],
  ['poll',      'Polling Grup',     'Buat polling untuk anggota grup'],
  ['vote',      'Vote',             'Voting untuk pilihan tertentu'],
  ['event_grp', 'Event Grup',       'Buat event/acara grup'],
  ['schedule',  'Jadwal Acara',     'Jadwal acara grup'],
  ['reminder',  'Pengingat Grup',   'Set pengingat untuk grup'],
  ['pinmsg',    'Pin Pesan',        'Pin pesan penting'],
  ['unpinmsg',  'Unpin Pesan',      'Unpin pesan yang sudah dipin'],
  ['listnote',  'Catatan Grup',     'Lihat semua catatan grup'],
  ['addnote',   'Tambah Catatan',   'Tambah catatan penting grup'],
  ['delnote',   'Hapus Catatan',    'Hapus catatan dari grup'],
  ['report',    'Laporkan Member',  'Laporkan member ke owner'],
  ['warn',      'Warn Member',      'Beri peringatan ke member'],
  ['warnlist',  'Daftar Warning',   'Lihat daftar warning member'],
  ['clearwarn', 'Hapus Warning',    'Hapus warning member'],
  ['rules',     'Aturan Grup',      'Lihat aturan grup'],
  ['setrules',  'Set Aturan',       'Atur aturan grup baru'],
  ['slowmode',  'Slow Mode',        'Aktifkan slow mode kirim pesan'],
  ['broadcast_grp','Broadcast Grup','Kirim pesan ke semua member satu per satu'],
  ['survey',    'Survey Grup',      'Buat survey pendapat anggota'],
  ['lottery_grp','Lotere Grup',     'Lotere berhadiah di grup'],
  ['giveaway',  'Giveaway',         'Adakan giveaway di grup'],
  ['lucky_draw','Lucky Draw',       'Lucky draw di grup'],
  ['menfess',   'Menfess',          'Kirim menfess anonim di grup'],
  ['confess',   'Confess Anonim',   'Confess anonim ke grup'],
  ['saran_grp', 'Kotak Saran',      'Kirim saran anonim ke admin'],
])

// ══════════════════════════════════════════
// 12. OWNER COMMANDS  ~100 fitur
// ══════════════════════════════════════════
batch('owner', [
  ['broadcast', 'Broadcast',        'Kirim pesan ke semua chat'],
  ['bcgroup',   'BC ke Grup',       'Broadcast ke semua grup'],
  ['bcprivate', 'BC ke Private',    'Broadcast ke semua chat private'],
  ['block',     'Block User',       'Blokir nomor tertentu'],
  ['unblock',   'Unblock User',     'Buka blokir nomor'],
  ['blocklist', 'Daftar Blokir',    'Lihat semua nomor yang diblokir'],
  ['join',      'Join Grup',        'Bot join grup via link'],
  ['leave',     'Leave Grup',       'Bot keluar dari grup'],
  ['restart',   'Restart Bot',      'Restart bot'],
  ['shutdown',  'Shutdown Bot',     'Matikan bot'],
  ['update',    'Update Bot',       'Update bot ke versi terbaru'],
  ['cleardb',   'Clear Database',   'Bersihkan data cache database'],
  ['backupdb',  'Backup Database',  'Backup database bot'],
  ['restoredb', 'Restore Database', 'Restore database dari backup'],
  ['addpremium','Tambah Premium',   'Tambahkan user ke daftar premium'],
  ['delpremium','Hapus Premium',    'Hapus user dari premium'],
  ['listpremium','List Premium',    'Daftar semua user premium'],
  ['addban',    'Ban User',         'Ban user dari pakai bot'],
  ['delban',    'Unban User',       'Unban user'],
  ['listban',   'List Ban',         'Daftar user yang dibanned'],
  ['addvip',    'Tambah VIP',       'Tambah user ke daftar VIP'],
  ['delvip',    'Hapus VIP',        'Hapus user dari VIP'],
  ['listvip',   'List VIP',         'Daftar user VIP'],
  ['acc',       'Approve Order',    'Approve konfirmasi pembayaran'],
  ['reject',    'Reject Order',     'Tolak order/konfirmasi'],
  ['listorder', 'List Order',       'Lihat semua order pending'],
  ['setbio',    'Set Bio',          'Ubah bio/status bot'],
  ['setpp',     'Set Foto Profil',  'Ubah foto profil bot'],
  ['setname_bot','Set Nama Bot',    'Ubah nama bot di WA'],
  ['mode',      'Mode Bot',         'Ubah mode bot (self/public/group)'],
  ['modepublic','Mode Public',      'Bot bisa dipakai semua orang'],
  ['modeself',  'Mode Self',        'Bot hanya bisa dipakai owner'],
  ['modegroup', 'Mode Group',       'Bot hanya aktif di grup'],
  ['status',    'Status Bot',       'Cek status dan statistik bot'],
  ['stats_detail','Statistik Bot',  'Statistik lengkap penggunaan bot'],
  ['listcmd',   'List Command',     'Daftar semua command aktif'],
  ['enablefeat','Enable Fitur',     'Aktifkan fitur tertentu'],
  ['disablefeat','Disable Fitur',   'Nonaktifkan fitur tertentu'],
  ['setprefix', 'Ganti Prefix',     'Ubah prefix bot sementara'],
  ['slowbot',   'Slow Mode Bot',    'Atur delay antar respon bot'],
  ['log',       'Lihat Log',        'Lihat log aktivitas bot terbaru'],
  ['clearlog',  'Clear Log',        'Bersihkan log bot'],
  ['sendto',    'Kirim ke JID',     'Kirim pesan ke JID tertentu'],
  ['testcmd',   'Test Command',     'Test command tertentu'],
  ['reload',    'Reload Module',    'Reload modul fitur tertentu'],
  ['botcredit', 'Bot Credits',      'Lihat kredit pembuat bot'],
  ['privacy',   'Privacy Check',    'Cek siapa yang bisa lihat status bot'],
  ['online',    'Toggle Online',    'Toggle status online bot'],
  ['autoread',  'Toggle Auto Read', 'Toggle auto baca pesan'],
  ['autotyping','Toggle Typing',    'Toggle indikator mengetik'],
  ['autoonline','Toggle Auto Online','Toggle status online otomatis'],
])

// ══════════════════════════════════════════
// 13. STORE & ECONOMY  ~200 fitur
// ══════════════════════════════════════════
batch('store', [
  ['listproduk','List Produk',      'Lihat semua produk di toko'],
  ['infoproduk','Info Produk',      'Detail info satu produk'],
  ['beli',      'Beli Produk',      'Beli produk dari toko'],
  ['konfirmasi','Konfirmasi Bayar', 'Kirim konfirmasi pembayaran'],
  ['saldo',     'Cek Saldo',        'Cek saldo akun'],
  ['topup',     'Topup Saldo',      'Request topup saldo'],
  ['transfer',  'Transfer Saldo',   'Transfer saldo ke user lain'],
  ['riwayat',   'Riwayat Bayar',    'Riwayat transaksi pembayaran'],
  ['orderstatus','Status Order',    'Cek status pesanan'],
  ['cancelorder','Cancel Order',    'Batalkan pesanan yang belum diproses'],
  ['refund',    'Refund',           'Request refund pesanan'],
  ['invoice',   'Invoice',          'Lihat invoice pesanan'],
  ['receipt',   'Kwitansi',         'Download kwitansi pembayaran'],
  ['promo',     'Lihat Promo',      'Lihat kode promo aktif'],
  ['redeem',    'Redeem Kode',      'Gunakan kode voucher/promo'],
  ['referral',  'Kode Referral',    'Lihat kode referral kamu'],
  ['voucher',   'Buat Voucher',     'Buat kode voucher (owner)'],
  ['flashsale', 'Flash Sale',       'Lihat flash sale terbatas'],
  ['wishlist',  'Wishlist',         'Tambah/lihat wishlist produk'],
  ['cart',      'Keranjang',        'Lihat keranjang belanja'],
  ['addcart',   'Tambah Keranjang', 'Tambah produk ke keranjang'],
  ['delcart',   'Hapus Keranjang',  'Hapus dari keranjang'],
  ['checkout',  'Checkout',         'Proses semua item di keranjang'],
  ['review_prod','Review Produk',   'Beri ulasan untuk produk'],
  ['listreview','List Ulasan',      'Lihat ulasan produk'],
  ['bestseller','Best Seller',      'Produk terlaris'],
  ['newprod',   'Produk Baru',      'Produk terbaru di toko'],
  ['searchprod','Cari Produk',      'Cari produk berdasarkan kata kunci'],
  ['catprod',   'Kategori Produk',  'Lihat produk berdasarkan kategori'],
  ['stockprod', 'Stok Produk',      'Cek stok produk tertentu'],
  ['pricelist', 'Daftar Harga',     'Lihat daftar harga semua produk'],
  ['affiliate', 'Program Afiliasi', 'Info program afiliasi bot'],
  ['komisi',    'Cek Komisi',       'Cek total komisi dari referral'],
  ['tarik',     'Tarik Komisi',     'Tarik komisi ke rekening'],
  ['poin',      'Poin Belanja',     'Lihat poin reward dari belanja'],
  ['tukar_poin','Tukar Poin',       'Tukar poin dengan diskon/produk'],
  ['level_user','Level Member',     'Lihat level membership kamu'],
  ['benefit',   'Benefit Member',   'Lihat benefit setiap level member'],
  ['upgrade',   'Upgrade Member',   'Upgrade level membership'],
])

// ══════════════════════════════════════════
// 14. STALK & SOCIAL  ~80 fitur
// ══════════════════════════════════════════
batch('stalk', [
  ['stalkig',   'Stalk Instagram',  'Info profil Instagram publik'],
  ['stalktiktok','Stalk TikTok',    'Info profil TikTok'],
  ['stalktwitter','Stalk Twitter',  'Info profil Twitter/X'],
  ['stalkfb',   'Stalk Facebook',   'Info halaman Facebook publik'],
  ['stalkgithub','Stalk GitHub',    'Info profil developer GitHub'],
  ['stalkyoutube','Stalk YouTube',  'Info channel YouTube'],
  ['stalkspotify','Stalk Spotify',  'Info profil Spotify'],
  ['stalklinkedin','Stalk LinkedIn','Info profil LinkedIn publik'],
  ['stalkpinterest','Stalk Pinterest','Info akun Pinterest'],
  ['stalksnap', 'Stalk Snapchat',   'Info profil Snapchat'],
  ['stalknomor','Info Nomor WA',    'Cek info nomor WhatsApp'],
  ['checkwa',   'Cek WA Aktif',     'Cek apakah nomor ada di WA'],
  ['whois',     'WHOIS Domain',     'Info domain/IP WHOIS'],
  ['dnslookup', 'DNS Lookup',       'Cek record DNS domain'],
  ['sslcheck',  'SSL Check',        'Cek sertifikat SSL website'],
  ['pagerank',  'PageRank',         'Estimasi popularitas website'],
  ['websiteinfo','Website Info',    'Teknologi yang dipakai website'],
  ['alexa',     'Alexa Rank',       'Ranking website di internet'],
  ['socialcheck','Social Check',    'Cek username di berbagai platform'],
  ['usercheck', 'Username Check',   'Apakah username tersedia di platform'],
  ['emailchecker','Email Checker',  'Validasi dan info email'],
  ['leakedcheck','Data Breach Check','Cek email bocor di breach database'],
  ['phoneinfo', 'Info Nomor HP',    'Cari info dari nomor HP'],
  ['ipgeo',     'IP Geolocation',   'Lokasi geografis dari IP address'],
  ['traceroute','Traceroute',       'Trace rute network ke host'],
  ['portcheck', 'Cek Port',         'Cek apakah port terbuka'],
  ['headercheck','HTTP Headers',    'Lihat HTTP response headers website'],
  ['robotstxt', 'robots.txt',       'Baca robots.txt website'],
  ['sitemapcheck','Sitemap',        'Cek sitemap website'],
  ['googlesearch','Google Preview', 'Preview tampilan di Google Search'],
  ['opengraph', 'Open Graph',       'Preview Open Graph website'],
  ['screenshot','Screenshot Web',   'Screenshot tampilan website desktop'],
  ['mobilesc',  'Mobile Screenshot','Screenshot tampilan mobile website'],
])

// ══════════════════════════════════════════
// 15. SOUND & AUDIO  ~100 fitur
// ══════════════════════════════════════════
batch('sound', [
  ['tts',       'Text to Speech',   'Ubah teks ke audio suara'],
  ['tts_id',    'TTS Indonesia',    'TTS bahasa Indonesia'],
  ['tts_en',    'TTS English',      'TTS bahasa Inggris'],
  ['tts_ja',    'TTS Jepang',       'TTS bahasa Jepang'],
  ['tts_ko',    'TTS Korea',        'TTS bahasa Korea'],
  ['tts_ar',    'TTS Arab',         'TTS bahasa Arab'],
  ['tts_ms',    'TTS Melayu',       'TTS bahasa Melayu'],
  ['stt',       'Speech to Text',   'Transkripsi audio/voice note ke teks'],
  ['ytmp3',     'YT MP3',           'Download YouTube audio MP3'],
  ['voicechanger','Voice Changer',  'Ubah pitch/efek suara'],
  ['pitch_up',  'Pitch Up',         'Naikkan pitch suara'],
  ['pitch_down','Pitch Down',       'Turunkan pitch suara'],
  ['speed_up',  'Speed Up',         'Percepat audio'],
  ['slow_down', 'Slow Down',        'Perlambat audio'],
  ['bassboost', 'Bass Boost',       'Tingkatkan bass audio'],
  ['reverb',    'Reverb Effect',    'Tambah efek reverb pada audio'],
  ['echo',      'Echo Effect',      'Tambah efek echo pada audio'],
  ['8daudio',   '8D Audio',         'Konversi audio ke efek 8D'],
  ['noise_reduce','Noise Reduce',   'Kurangi noise background audio'],
  ['normalize', 'Normalize Audio',  'Normalisasi volume audio'],
  ['trim_audio','Trim Audio',       'Potong bagian audio tertentu'],
  ['merge_audio','Gabung Audio',    'Gabungkan dua file audio'],
  ['sfx_applause','SFX Tepuk Tangan','Sound effect tepuk tangan'],
  ['sfx_laugh', 'SFX Tawa',        'Sound effect tawa'],
  ['sfx_boo',   'SFX Boo',          'Sound effect boo/mengejek'],
  ['sfx_tada',  'SFX Ta-Da',        'Sound effect ta-da victory'],
  ['sfx_fail',  'SFX Fail',         'Sound effect kegagalan lucu'],
  ['sfx_level_up','SFX Level Up',   'Sound effect level up RPG'],
  ['sfx_coin',  'SFX Koin',         'Sound effect koin diperoleh'],
  ['sfx_notification','SFX Notif',  'Sound effect notifikasi'],
  ['sfx_doorbell','SFX Bel Pintu',  'Sound effect bel pintu'],
  ['sfx_rain',  'SFX Hujan',        'Sound effect hujan'],
  ['sfx_thunder','SFX Petir',       'Sound effect petir'],
  ['sfx_ocean', 'SFX Laut',         'Sound effect deburan ombak'],
  ['sfx_forest','SFX Hutan',        'Sound effect suasana hutan'],
  ['sfx_crowd', 'SFX Keramaian',    'Sound effect keramaian/pasar'],
  ['sfx_alarm', 'SFX Alarm',        'Sound effect alarm'],
  ['sfx_siren', 'SFX Sirine',       'Sound effect sirine'],
  ['sfx_glass', 'SFX Pecah Kaca',   'Sound effect kaca pecah'],
  ['sfx_explosion','SFX Ledakan',   'Sound effect ledakan'],
  ['adzansubuh','Adzan Subuh',      'Audio adzan subuh'],
  ['adzandzuhur','Adzan Dzuhur',    'Audio adzan dzuhur'],
  ['adzan_ashar','Adzan Ashar',     'Audio adzan ashar'],
  ['adzan_magrib','Adzan Maghrib',  'Audio adzan maghrib'],
  ['adzan_isya','Adzan Isya',       'Audio adzan isya'],
  ['murottal',  'Murottal',         'Audio murottal Al-Quran'],
  ['sholawat',  'Sholawat',         'Audio sholawat Nabi'],
  ['zikir',     'Zikir',            'Audio bacaan zikir'],
  ['instrumental','Musik Instrumental','Musik instrumental background'],
  ['lofihiphop','Lo-Fi Hip Hop',    'Stream Lo-Fi hip hop music'],
  ['classicmusic','Musik Klasik',   'Musik klasik instrumental'],
  ['jazzmusic', 'Jazz Music',       'Musik jazz santai'],
])

// ══════════════════════════════════════════
// 16. CONVERT & FORMAT  ~200 fitur
// ══════════════════════════════════════════
batch('convert', [
  ['tobase64',  'Teks → Base64',    'Encode teks ke Base64'],
  ['frombase64','Base64 → Teks',    'Decode Base64 ke teks'],
  ['tohex',     'Teks → Hex',       'Encode teks ke hexadecimal'],
  ['fromhex',   'Hex → Teks',       'Decode hex ke teks'],
  ['tobinary',  'Teks → Biner',     'Encode teks ke binary'],
  ['frombinary','Biner → Teks',     'Decode binary ke teks'],
  ['tooct',     'Teks → Oktal',     'Encode teks ke oktal'],
  ['tourl',     'URL Encode',       'URL encode string'],
  ['fromurl',   'URL Decode',       'URL decode string'],
  ['tohtml',    'HTML Entities',    'Encode ke HTML entities'],
  ['fromhtml',  'From HTML Ent',    'Decode HTML entities'],
  ['tojson',    'Format JSON',      'Format/beautify JSON'],
  ['minifyjson','Minify JSON',      'Minify/compress JSON'],
  ['validatejson','Validate JSON',  'Validasi apakah JSON valid'],
  ['xmltoJSON', 'XML → JSON',       'Konversi XML ke JSON'],
  ['jsontoxml', 'JSON → XML',       'Konversi JSON ke XML'],
  ['csvtojson', 'CSV → JSON',       'Konversi CSV ke JSON'],
  ['jsontoCsv', 'JSON → CSV',       'Konversi JSON ke CSV'],
  ['markdowntohtml','MD → HTML',    'Konversi Markdown ke HTML'],
  ['htmltomd',  'HTML → Markdown',  'Konversi HTML ke Markdown'],
  ['toimgpng',  'Konversi ke PNG',  'Konversi gambar ke format PNG'],
  ['toimgjpg',  'Konversi ke JPG',  'Konversi gambar ke format JPG'],
  ['toimgwebp', 'Konversi ke WebP', 'Konversi gambar ke format WebP'],
  ['toimgavif', 'Konversi ke AVIF', 'Konversi gambar ke format AVIF'],
  ['togif_img', 'Konversi ke GIF',  'Konversi gambar/video ke GIF'],
  ['tomp4',     'Video → MP4',      'Konversi video ke format MP4'],
  ['tomp3',     'Audio → MP3',      'Konversi audio ke format MP3'],
  ['toaac',     'Audio → AAC',      'Konversi audio ke format AAC'],
  ['toogg',     'Audio → OGG',      'Konversi audio ke format OGG'],
  ['toflac',    'Audio → FLAC',     'Konversi audio ke format FLAC'],
  ['towav',     'Audio → WAV',      'Konversi audio ke format WAV'],
  ['compress_img','Kompres Gambar', 'Kompres ukuran file gambar'],
  ['compress_vid','Kompres Video',  'Kompres ukuran file video'],
  ['compress_audio','Kompres Audio','Kompres ukuran file audio'],
  ['imgresolution','Ubah Resolusi', 'Ubah resolusi gambar'],
  ['vidresolution','Resolusi Video','Ubah resolusi video'],
  ['fps_change','Ubah FPS',         'Ubah frame rate video'],
  ['vidspeed',  'Kecepatan Video',  'Ubah kecepatan video'],
  ['vidreverse','Balik Video',      'Balik urutan frame video'],
  ['vidclip',   'Clip Video',       'Potong segmen video'],
  ['vidaudio',  'Ekstrak Audio',    'Ekstrak audio dari video'],
  ['addsubtitle','Tambah Subtitle', 'Tambahkan subtitle ke video'],
  ['pdfmerge',  'Gabung PDF',       'Gabungkan beberapa PDF menjadi satu'],
  ['pdfsplit',  'Pisah PDF',        'Pisahkan halaman PDF'],
  ['pdftoimg',  'PDF → Gambar',     'Konversi halaman PDF ke gambar'],
  ['imgtopdf',  'Gambar → PDF',     'Konversi gambar ke PDF'],
  ['pdfcompress','Kompres PDF',     'Kompres ukuran file PDF'],
  ['pdfwatermark','Watermark PDF',  'Tambahkan watermark ke PDF'],
  ['docxtopdf', 'Word → PDF',       'Konversi dokumen Word ke PDF'],
  ['pptxtopdf', 'PPT → PDF',        'Konversi PowerPoint ke PDF'],
  ['xlsxtopdf', 'Excel → PDF',      'Konversi Excel ke PDF'],
  ['texttopdf', 'Teks → PDF',       'Buat PDF dari teks'],
  ['htmltopdf', 'HTML → PDF',       'Konversi halaman HTML/web ke PDF'],
  ['qr_decode', 'Decode QR',        'Baca isi QR code dari gambar'],
  ['barcode_gen','Buat Barcode',    'Generate barcode dari teks/nomor'],
  ['barcode_read','Baca Barcode',   'Baca barcode dari gambar'],
  ['exceltocsv','Excel → CSV',      'Konversi file Excel ke CSV'],
  ['csvtoexcel','CSV → Excel',      'Konversi CSV ke file Excel'],
  ['zipcreate', 'Buat ZIP',         'Kompres file ke format ZIP'],
  ['zipextract','Ekstrak ZIP',      'Lihat isi file ZIP'],
])

// ══════════════════════════════════════════
// 17. SEARCH  ~120 fitur
// ══════════════════════════════════════════
batch('search', [
  ['google',    'Google Search',    'Cari di Google dan tampilkan hasil'],
  ['googlenews','Google News',      'Berita terkini dari Google News'],
  ['bing',      'Bing Search',      'Cari di Bing'],
  ['wiki',      'Wikipedia',        'Cari artikel Wikipedia'],
  ['wikid',     'Wikipedia ID',     'Artikel Wikipedia bahasa Indonesia'],
  ['wikisum',   'Wiki Summary',     'Ringkasan artikel Wikipedia'],
  ['youtube_search','YouTube Search','Cari video di YouTube'],
  ['spotify_search','Spotify Search','Cari lagu/artis di Spotify'],
  ['moviedb',   'Movie Search',     'Cari film di database'],
  ['tvdb',      'TV Show Search',   'Cari serial TV'],
  ['imdb',      'IMDB Search',      'Cari di IMDB'],
  ['mal',       'MyAnimeList',      'Cari anime/manga di MAL'],
  ['goodreads', 'Goodreads',        'Cari buku di Goodreads'],
  ['openlibrary','Open Library',    'Cari buku di Open Library'],
  ['arxiv',     'ArXiv Papers',     'Cari makalah ilmiah di ArXiv'],
  ['scholar',   'Google Scholar',   'Cari artikel akademik'],
  ['npm',       'NPM Search',       'Cari paket Node.js di NPM'],
  ['pypi',      'PyPI Search',      'Cari paket Python di PyPI'],
  ['github_search','GitHub Search', 'Cari repository GitHub'],
  ['stackoverflow','Stack Overflow','Cari solusi programming'],
  ['steam',     'Steam Search',     'Cari game di Steam'],
  ['playstore_search','Play Store', 'Cari app di Google Play Store'],
  ['appstore_search','App Store',   'Cari app di Apple App Store'],
  ['lazadaid',  'Lazada Search',    'Cari produk di Lazada ID'],
  ['tokopedia', 'Tokopedia Search', 'Cari produk di Tokopedia'],
  ['shopee',    'Shopee Search',    'Cari produk di Shopee'],
  ['bukalapak', 'Bukalapak Search', 'Cari produk di Bukalapak'],
  ['blibli',    'Blibli Search',    'Cari produk di Blibli'],
  ['traveloka', 'Traveloka',        'Cari tiket/hotel di Traveloka'],
  ['tiketcom',  'Tiket.com',        'Cari tiket di Tiket.com'],
  ['fooddelivery','Food Delivery',  'Cari menu makanan delivery'],
  ['gofood',    'GoFood',           'Cari restoran GoFood'],
  ['grabfood',  'GrabFood',         'Cari restoran GrabFood'],
  ['shopeefood','ShopeeFood',       'Cari restoran ShopeeFood'],
  ['kbbi',      'Kamus KBBI',       'Cari arti kata di KBBI'],
  ['synonymid', 'Sinonim Indonesia','Cari sinonim kata Indonesia'],
  ['antonymid', 'Antonim Indonesia','Cari antonim kata Indonesia'],
  ['kamus_en',  'Kamus Inggris',    'Kamus Indonesia-Inggris'],
  ['thesaurus', 'Thesaurus',        'Cari sinonim Inggris di Thesaurus'],
  ['urban',     'Urban Dictionary', 'Cari definisi di Urban Dictionary'],
  ['gifysearch', 'GIPHY Search',    'Cari GIF di GIPHY'],
  ['tenorsearch','Tenor Search',    'Cari GIF di Tenor'],
  ['unsplash_search','Unsplash',    'Cari foto di Unsplash'],
  ['pexels_search','Pexels',        'Cari foto di Pexels'],
  ['pixabay_search','Pixabay',      'Cari gambar di Pixabay'],
  ['soundcloudsearch','SoundCloud', 'Cari lagu di SoundCloud'],
  ['deezer_search','Deezer',        'Cari lagu di Deezer'],
  ['lyricsearch','Cari Lirik',      'Cari lirik lagu'],
  ['chordsearch','Cari Chord',      'Cari chord gitar lagu'],
  ['tabssearch', 'Cari Tabs',       'Cari guitar tabs'],
  ['recipedb',  'Database Resep',   'Cari resep di database masakan'],
  ['nutritiondb','Nutrition DB',    'Cari info nutrisi makanan'],
  ['caloriefood','Kalori Makanan',  'Cek kalori makanan tertentu'],
  ['medicineid','Info Obat',        'Cari info obat/farmasi Indonesia'],
  ['icdcode',   'ICD Code',         'Cari kode ICD penyakit'],
  ['flightsearch','Cari Penerbangan','Cari jadwal penerbangan'],
  ['trainstatus','Status Kereta',   'Status dan jadwal kereta KAI'],
  ['busnow',    'Jadwal Bus',       'Cari jadwal bus antar kota'],
  ['taxi',      'Estimasi Taksi',   'Estimasi biaya taksi'],
])

// ══════════════════════════════════════════
// 18. EDUCATION  ~200 fitur
// ══════════════════════════════════════════
const ELEMENTS = [
  ['H','Hidrogen'],['He','Helium'],['Li','Litium'],['Be','Berilium'],['B','Boron'],
  ['C','Karbon'],['N','Nitrogen'],['O','Oksigen'],['F','Fluor'],['Ne','Neon'],
  ['Na','Natrium'],['Mg','Magnesium'],['Al','Aluminium'],['Si','Silikon'],['P','Fosfor'],
  ['S','Sulfur/Belerang'],['Cl','Klorin'],['Ar','Argon'],['K','Kalium'],['Ca','Kalsium'],
  ['Fe','Besi/Ferrum'],['Cu','Tembaga/Kuprum'],['Zn','Seng/Zinkum'],['Ag','Perak'],
  ['Au','Emas/Aurum'],['Hg','Raksa/Hidrargium'],['Pb','Timbal/Plumbum'],['U','Uranium'],
  ['Pu','Plutonium'],['Ra','Radium'],['Rn','Radon'],['Xe','Xenon'],['Kr','Kripton'],
]
ELEMENTS.forEach(([sym, name]) => {
  f('education', 'el_'+sym.toLowerCase(), 'Unsur: '+name, 'Informasi unsur kimia '+name+' ('+sym+')', 'element_info', { symbol:sym })
})

batch('education', [
  ['rumus_fisika','Rumus Fisika',   'Koleksi rumus fisika dasar-lanjut'],
  ['rumus_kimia','Rumus Kimia',     'Koleksi rumus kimia'],
  ['rumus_mtk',  'Rumus Matematika','Koleksi rumus matematika'],
  ['rumus_bio',  'Rumus Biologi',   'Rumus dan konsep biologi'],
  ['tabelperiodik','Tabel Periodik','Tabel periodik unsur lengkap'],
  ['valensi',   'Valensi Unsur',   'Tabel elektron valensi unsur'],
  ['oksidasi',  'Biloks',          'Bilangan oksidasi senyawa'],
  ['sifat_asam','Asam-Basa-Garam', 'Sifat dan contoh asam, basa, garam'],
  ['hukum_newton','Hukum Newton',  'Hukum Newton 1, 2, 3'],
  ['termodinamika','Termodinamika','Hukum-hukum termodinamika'],
  ['listrik',   'Listrik',         'Rumus dan konsep listrik'],
  ['optik',     'Optik',           'Rumus dan konsep optik cahaya'],
  ['gelombang', 'Gelombang',       'Rumus dan jenis gelombang'],
  ['matriks',   'Matriks',         'Operasi matriks matematika'],
  ['vektork',   'Vektor',          'Operasi vektor 2D dan 3D'],
  ['turunan',   'Turunan',         'Rumus dan contoh turunan/diferensial'],
  ['integral',  'Integral',        'Rumus dan contoh integral'],
  ['limit',     'Limit',           'Konsep dan rumus limit'],
  ['statistik', 'Statistika',      'Rumus mean, median, modus, SD'],
  ['probabilitas','Probabilitas',  'Rumus peluang/probabilitas'],
  ['geometri',  'Geometri',        'Rumus bangun datar dan ruang'],
  ['trigonometri','Trigonometri',  'Identitas dan rumus trigonometri'],
  ['logaritma', 'Logaritma',       'Sifat dan rumus logaritma'],
  ['eksponen',  'Eksponen',        'Sifat dan rumus eksponen'],
  ['himpunan',  'Teori Himpunan',  'Konsep dan operasi himpunan'],
  ['kombinatorik','Kombinatorik',  'Permutasi, kombinasi, faktorial'],
  ['aljabar',   'Aljabar',         'Aljabar linear dan persamaan'],
  ['fungsi',    'Fungsi',          'Jenis dan sifat fungsi matematika'],
  ['barisan',   'Barisan & Deret', 'Aritmatika dan geometri'],
  ['sejarah_id','Sejarah Indonesia','Timeline sejarah Indonesia'],
  ['pahlawan',  'Pahlawan Nasional','Info pahlawan nasional Indonesia'],
  ['proklamasi','Proklamasi',      'Isi dan sejarah proklamasi kemerdekaan'],
  ['pancasila', 'Pancasila',       'Butir-butir Pancasila dan artinya'],
  ['uud45',     'UUD 1945',        'Isi UUD 1945 per pasal'],
  ['presiden_id','Presiden RI',    'Daftar dan profil presiden Indonesia'],
  ['geography_id','Geografi ID',   'Geografi Indonesia lengkap'],
  ['planet',    'Info Planet',     'Info 8 planet tata surya'],
  ['bintanginfo','Info Bintang',   'Jenis dan info bintang'],
  ['galaksi',   'Info Galaksi',    'Jenis dan info galaksi'],
  ['blackhole', 'Black Hole',      'Info lubang hitam'],
  ['pemrograman','Info Pemrograman','Info bahasa pemrograman populer'],
  ['algoritma', 'Algoritma',       'Penjelasan algoritma populer'],
  ['strukturdata','Struktur Data', 'Penjelasan struktur data'],
  ['bigO',      'Big-O Notation',  'Penjelasan kompleksitas algoritma'],
  ['database',  'Database',        'Konsep dan jenis database'],
  ['jaringan',  'Jaringan Komputer','Konsep jaringan dan protokol'],
  ['os_concept','OS Concept',      'Konsep sistem operasi'],
  ['cybersec',  'Keamanan Siber',  'Konsep dasar cybersecurity'],
  ['crypto_info','Kriptografi',    'Konsep kriptografi dasar'],
  ['biologi_sel','Biologi Sel',    'Struktur dan fungsi sel'],
  ['fotosintesis','Fotosintesis',  'Proses fotosintesis'],
  ['respirasi', 'Respirasi',       'Proses respirasi seluler'],
  ['genetika',  'Genetika',        'Konsep DNA, gen, kromosom'],
  ['evolusi',   'Evolusi',         'Teori evolusi Darwin'],
  ['ekologi',   'Ekologi',         'Rantai makanan dan ekosistem'],
])

// ══════════════════════════════════════════
// 19. ISLAM & AGAMA  ~100 fitur
// ══════════════════════════════════════════
batch('islam', [
  ['quran',     'Baca Al-Quran',    'Baca ayat Al-Quran'],
  ['quransearch','Cari Ayat',       'Cari ayat Al-Quran berdasarkan kata kunci'],
  ['surahinfo', 'Info Surah',       'Informasi detail surah Al-Quran'],
  ['listsurah', 'Daftar Surah',     'Daftar 114 surah Al-Quran'],
  ['ayatrandom','Ayat Random',      'Ayat Al-Quran acak + terjemahan'],
  ['juz',       'Juz Al-Quran',     'Baca konten per juz'],
  ['hadits',    'Hadits',           'Hadits dari berbagai riwayat'],
  ['haditsrandom','Hadits Random',  'Hadits acak sahih'],
  ['haditsbukhari','Hadits Bukhari','Hadits dari Shahih Bukhari'],
  ['haditsmuslim','Hadits Muslim',  'Hadits dari Shahih Muslim'],
  ['sholat',    'Jadwal Sholat',    'Jadwal waktu sholat kota tertentu'],
  ['sholat_notif','Notif Sholat',   'Pengingat waktu sholat'],
  ['qiblat',    'Arah Kiblat',      'Arah kiblat dari lokasi'],
  ['hijriah',   'Kalender Hijriah', 'Konversi tanggal masehi ke hijriah'],
  ['puasa',     'Jadwal Puasa',     'Jadwal imsakiyah kota tertentu'],
  ['doa',       'Doa Harian',       'Doa sehari-hari dalam Islam'],
  ['doa_makan', 'Doa Makan',        'Doa sebelum dan sesudah makan'],
  ['doa_tidur', 'Doa Tidur',        'Doa sebelum tidur'],
  ['doa_bangun','Doa Bangun',       'Doa setelah bangun tidur'],
  ['doa_sholat','Doa dalam Sholat', 'Bacaan doa dalam sholat'],
  ['dzikir',    'Bacaan Dzikir',    'Bacaan dzikir harian'],
  ['asmaul',    'Asmaul Husna',     '99 Asmaul Husna dan artinya'],
  ['rukun_islam','Rukun Islam',     'Penjelasan 5 Rukun Islam'],
  ['rukun_iman','Rukun Iman',       'Penjelasan 6 Rukun Iman'],
  ['sifat_allah','Sifat Allah',     '20 sifat wajib Allah'],
  ['nabi',      'Kisah Nabi',       'Kisah singkat para Nabi'],
  ['sahabat',   'Kisah Sahabat',    'Kisah sahabat Nabi Muhammad SAW'],
  ['sejarah_islam','Sejarah Islam', 'Timeline sejarah Islam'],
  ['zakat',     'Kalkulator Zakat', 'Hitung zakat mal dan penghasilan'],
  ['infaq',     'Info Infaq/Sedekah','Keutamaan infaq dan sedekah'],
  ['waris',     'Hukum Waris',      'Kalkulator pembagian waris Islam'],
  ['doa_qunut', 'Doa Qunut',        'Bacaan doa qunut sholat witir'],
  ['khotbah',   'Khotbah Jumat',    'Contoh khotbah Jumat singkat'],
  ['maulid',    'Maulid Nabi',      'Info dan jadwal maulid nabi'],
  ['isra_miraj','Isra Miraj',       'Kisah dan info Isra Miraj'],
  ['ramadan',   'Info Ramadan',     'Info seputar bulan Ramadan'],
  ['lebaran',   'Lebaran Countdown','Hitung mundur Idul Fitri'],
  ['haji',      'Info Haji',        'Panduan dan info ibadah haji'],
  ['umrah',     'Info Umrah',       'Panduan dan info ibadah umrah'],
  ['shalawat',  'Shalawat Nabi',    'Bacaan dan audio shalawat Nabi'],
  ['tajwid',    'Ilmu Tajwid',      'Hukum tajwid dalam membaca Al-Quran'],
])

// ══════════════════════════════════════════
// 20. DEVELOPER TOOLS  ~100 fitur
// ══════════════════════════════════════════
batch('developer', [
  ['encode_jwt','Encode JWT',       'Buat token JWT'],
  ['decode_jwt','Decode JWT',       'Decode dan verifikasi JWT token'],
  ['regex_test','Regex Tester',     'Test regex pattern terhadap string'],
  ['json_validate','Validate JSON', 'Validasi format JSON'],
  ['json_format','Format JSON',     'Pretty print JSON'],
  ['json_minify','Minify JSON',     'Minify JSON untuk produksi'],
  ['yaml_valid','Validate YAML',    'Validasi format YAML'],
  ['yaml_tojson','YAML → JSON',     'Konversi YAML ke JSON'],
  ['sql_format','Format SQL',       'Format/beautify query SQL'],
  ['css_minify','Minify CSS',       'Minify kode CSS'],
  ['js_minify', 'Minify JS',        'Minify kode JavaScript'],
  ['html_format','Format HTML',     'Format/beautify kode HTML'],
  ['color_hex', 'Color HEX → RGB',  'Konversi HEX ke RGB'],
  ['color_rgb', 'Color RGB → HEX',  'Konversi RGB ke HEX'],
  ['color_hsl', 'Color HSL',        'Konversi HSL → HEX/RGB'],
  ['ip_calc',   'IP Calculator',    'Hitung subnet mask dan CIDR'],
  ['mac_vendor','MAC Vendor',       'Cek vendor dari MAC address'],
  ['port_info', 'Info Port',        'Info service umum tiap port'],
  ['http_status','HTTP Status',     'Penjelasan HTTP status code'],
  ['curl_builder','cURL Builder',   'Build cURL command dari parameter'],
  ['cron_parse','Cron Parser',      'Parse dan jelaskan cron expression'],
  ['cron_gen',  'Cron Generator',   'Generate cron expression'],
  ['timestamp_now','Timestamp Now', 'Unix timestamp sekarang'],
  ['date_parse','Parse Date',       'Parse string tanggal ke format lain'],
  ['semver',    'SemVer Parser',    'Parse dan bandingkan versi semver'],
  ['lorem',     'Lorem Ipsum',      'Generate text Lorem Ipsum'],
  ['faker_name','Faker: Nama',      'Generate nama palsu realistic'],
  ['faker_email','Faker: Email',    'Generate email palsu realistic'],
  ['faker_addr','Faker: Alamat',    'Generate alamat palsu realistic'],
  ['faker_phone','Faker: Telepon',  'Generate nomor telepon palsu'],
  ['faker_credit','Faker: Kartu',   'Generate nomor kartu palsu (test)'],
  ['faker_iban','Faker: IBAN',      'Generate IBAN palsu untuk testing'],
  ['mock_api',  'Mock API',         'Buat endpoint API mock sederhana'],
  ['webhook_test','Webhook Test',   'Test webhook URL'],
  ['ssl_info',  'SSL Info',         'Info sertifikat SSL domain'],
  ['whois_domain','WHOIS Domain',   'Info registrar domain'],
  ['dns_check', 'DNS Check',        'Cek record A, MX, TXT, dll'],
  ['ping_host', 'Ping Host',        'Ping hostname/IP'],
  ['uptime_check','Uptime Check',   'Cek apakah website up atau down'],
  ['pageload',  'Page Load',        'Tes kecepatan loading halaman'],
  ['api_tester','API Tester',       'Test endpoint API sederhana'],
  ['base_convert','Base Converter', 'Konversi angka antar basis bilangan'],
  ['two_complement','Two\'s Comp',  'Hitung two\'s complement'],
  ['ieee754',   'IEEE 754',         'Representasi IEEE 754 floating point'],
  ['bit_ops',   'Bitwise Ops',      'Operasi bitwise AND OR XOR'],
  ['grep_sim',  'Grep Simulator',   'Filter baris teks seperti grep'],
  ['awk_sim',   'AWK Simulator',    'Proses teks seperti AWK'],
  ['jq_online', 'JQ Online',        'Query JSON dengan jq syntax'],
  ['xpath',     'XPath Tester',     'Test XPath query pada XML'],
])

// ══════════════════════════════════════════
// 21. HEALTH & WELLNESS  ~80 fitur
// ══════════════════════════════════════════
batch('health', [
  ['bmi_calc',  'Hitung BMI',       'Hitung Body Mass Index + kategori'],
  ['bmi_ideal', 'Berat Ideal',      'Hitung berat badan ideal'],
  ['kalori_harian','Kalori Harian', 'Kebutuhan kalori harian (TDEE)'],
  ['kalori_makan','Kalori Makanan', 'Kalori dari makanan Indonesia'],
  ['nutrisi',   'Info Nutrisi',     'Info kandungan nutrisi makanan'],
  ['diet_program','Program Diet',   'Program diet berbasis kalori'],
  ['workout_plan','Rencana Olahraga','Rencana workout mingguan'],
  ['push_up',   'Push Up Guide',    'Panduan melakukan push up'],
  ['sit_up',    'Sit Up Guide',     'Panduan melakukan sit up'],
  ['running',   'Running Guide',    'Panduan jogging/lari'],
  ['stretching','Stretching',       'Gerakan stretching untuk pemula'],
  ['yoga',      'Yoga Poses',       'Info gerakan yoga dasar'],
  ['meditasi',  'Meditasi',         'Panduan meditasi singkat'],
  ['tidur',     'Tips Tidur',       'Tips tidur yang berkualitas'],
  ['stres',     'Atasi Stres',      'Tips mengatasi stres'],
  ['depresi',   'Info Depresi',     'Tentang depresi dan cara bantu'],
  ['anxiety',   'Info Anxietas',    'Tentang kecemasan dan penanganannya'],
  ['obat_umum', 'Obat Umum',        'Info obat-obatan umum OTC'],
  ['pertolongan','P3K',             'Panduan pertolongan pertama'],
  ['cpr',       'CPR Guide',        'Panduan CPR/resusitasi'],
  ['demam',     'Info Demam',       'Menangani demam secara umum'],
  ['flu',       'Info Flu',         'Gejala dan penanganan flu'],
  ['covid',     'Info COVID-19',    'Info vaksin dan protokol kesehatan'],
  ['diabetes',  'Info Diabetes',    'Info umum diabetes mellitus'],
  ['hipertensi','Info Hipertensi',  'Info tekanan darah tinggi'],
  ['kolesterol','Info Kolesterol',  'Info kadar kolesterol'],
  ['tekanandarah','Tekanan Darah',  'Nilai normal tekanan darah'],
  ['guladarah', 'Gula Darah',       'Nilai normal gula darah'],
  ['goldar',    'Golongan Darah',   'Info golongan darah A, B, O, AB'],
  ['vitamins',  'Info Vitamin',     'Info vitamin dan manfaatnya'],
  ['minerals',  'Info Mineral',     'Info mineral dan manfaatnya'],
  ['puasa_kesehatan','Puasa Sehat', 'Manfaat puasa bagi kesehatan'],
])

// ══════════════════════════════════════════
// 22. FOOD & CULINARY  ~100 fitur
// ══════════════════════════════════════════
batch('food', [
  ['resep',     'Resep Masakan',    'Resep masakan Indonesia'],
  ['resep_id',  'Resep Nusantara',  'Resep masakan daerah Indonesia'],
  ['resep_simple','Resep Simpel',   'Resep mudah dan cepat'],
  ['resep_hemat','Resep Hemat',     'Resep lezat dengan bahan murah'],
  ['resep_sehat','Resep Sehat',     'Resep makanan bergizi'],
  ['resep_diet','Resep Diet',       'Resep masakan diet rendah kalori'],
  ['resep_vegan','Resep Vegan',     'Resep masakan tanpa hewani'],
  ['resep_bayi','Resep MPASI',      'Resep MPASI untuk bayi'],
  ['resep_kue', 'Resep Kue',        'Resep kue dan dessert'],
  ['resep_minuman','Resep Minuman', 'Resep minuman segar dan hangat'],
  ['kuliner_jakarta','Kuliner Jakarta','Kuliner khas Jakarta'],
  ['kuliner_jogja','Kuliner Jogja', 'Kuliner khas Yogyakarta'],
  ['kuliner_surabaya','Kuliner SBY','Kuliner khas Surabaya'],
  ['kuliner_padang','Kuliner Padang','Kuliner khas Padang'],
  ['kuliner_bali','Kuliner Bali',   'Kuliner khas Bali'],
  ['kuliner_makassar','Kuliner UJG','Kuliner khas Makassar'],
  ['kuliner_medan','Kuliner Medan', 'Kuliner khas Medan'],
  ['kuliner_bandung','Kuliner BDG', 'Kuliner khas Bandung'],
  ['masakan_cina','Masakan Cina',   'Resep masakan Cina populer'],
  ['masakan_jepang','Masakan Jepang','Resep masakan Jepang'],
  ['masakan_korea','Masakan Korea', 'Resep masakan Korea'],
  ['masakan_india','Masakan India', 'Resep masakan India'],
  ['masakan_arab','Masakan Arab',   'Resep masakan Arab/Timur Tengah'],
  ['masakan_barat','Masakan Barat', 'Resep masakan Barat/Eropa'],
  ['masakan_meksiko','Masakan Meksiko','Resep masakan Meksiko'],
  ['masakan_thai','Masakan Thailand','Resep masakan Thailand'],
  ['bahan_substitusi','Substitusi Bahan','Ganti bahan yang tidak ada'],
  ['tips_masak','Tips Memasak',     'Tips dan trik memasak'],
  ['bumbu',     'Info Bumbu',       'Info bumbu dan rempah Indonesia'],
  ['buah_info', 'Info Buah',        'Info nutrisi dan manfaat buah'],
  ['sayuran',   'Info Sayuran',     'Info nutrisi dan cara masak sayuran'],
  ['random_menu','Menu Acak',       'Ide menu makanan hari ini'],
  ['menu_mingguan','Menu Mingguan', 'Rencana menu makan seminggu'],
  ['belanja_list','Daftar Belanja', 'Generate daftar belanja dari menu'],
])

// ══════════════════════════════════════════
// 23. ENTERTAINMENT & MEDIA  ~80 fitur
// ══════════════════════════════════════════
batch('entertainment', [
  ['movie_info','Info Film',        'Info lengkap film dari TMDB'],
  ['movie_top', 'Film Terpopuler', 'Top film minggu/bulan ini'],
  ['movie_now', 'Sedang Tayang',   'Film yang sedang tayang di bioskop'],
  ['movie_rec', 'Rekomendasi Film','Rekomendasi film berdasarkan genre'],
  ['tvshow_info','Info Serial TV',  'Info lengkap serial TV'],
  ['tvshow_top','Serial Terpopuler','Top serial TV populer'],
  ['tvshow_upcoming','Serial Baru', 'Serial TV yang akan datang'],
  ['tvshow_rec','Rekomendasi Serial','Rekomendasi serial berdasarkan genre'],
  ['music_info','Info Musik',       'Info lagu/artis dari Spotify/MusicBrainz'],
  ['artist_info','Info Artis',      'Biografi dan diskografi artis'],
  ['album_info','Info Album',       'Info album dan tracklist'],
  ['chart_music','Music Chart',     'Top chart musik terkini'],
  ['lyrics',    'Cari Lirik',       'Cari lirik lagu dari LyricsOVH'],
  ['chord',     'Cari Chord Gitar','Chord gitar lagu populer'],
  ['tabs',      'Cari Guitar Tab', 'Guitar tabs dari Ultimate-Guitar'],
  ['book_info', 'Info Buku',        'Info buku dari Google Books/OpenLibrary'],
  ['book_top',  'Buku Terpopuler', 'Top buku best seller'],
  ['book_rec',  'Rekomendasi Buku','Rekomendasi buku berdasarkan genre'],
  ['game_info', 'Info Game',        'Info video game dari RAWG API'],
  ['game_top',  'Game Terpopuler', 'Top game berdasarkan rating'],
  ['game_new',  'Game Baru',        'Game terbaru dirilis'],
  ['game_rec',  'Rekomendasi Game','Rekomendasi game berdasarkan genre'],
  ['esports',   'Esports News',     'Berita dunia esports terkini'],
  ['berita',    'Berita Terkini',   'Berita terbaru dari portal ID'],
  ['berita_tech','Berita Teknologi','Berita teknologi terkini'],
  ['berita_olahraga','Berita Olahraga','Berita olahraga terkini'],
  ['berita_hiburan','Berita Hiburan','Berita hiburan dan selebriti'],
  ['viral',     'Konten Viral',     'Konten yang sedang viral'],
  ['trending',  'Trending',         'Topik trending di Twitter/Google'],
  ['podcast_rec','Podcast Rekom',   'Rekomendasi podcast bagus'],
  ['drama_korea','Drama Korea',     'Info dan rekomendasi drama Korea'],
  ['sinetron',  'Sinetron Indonesia','Jadwal tayang sinetron Indonesia'],
  ['radio_online','Radio Online',   'Daftar stasiun radio online Indonesia'],
])

// ══════════════════════════════════════════
// 24. GEOGRAPHY & TRAVEL  ~80 fitur
// ══════════════════════════════════════════
batch('geography', [
  ['negara',    'Info Negara',      'Info lengkap suatu negara'],
  ['ibukota',   'Ibu Kota',         'Ibu kota negara di dunia'],
  ['populasi',  'Populasi',         'Populasi kota/negara'],
  ['luas',      'Luas Wilayah',     'Luas wilayah negara/provinsi'],
  ['peta',      'Peta Lokasi',      'Lihat peta lokasi tertentu'],
  ['jarak',     'Hitung Jarak',     'Hitung jarak dua kota'],
  ['koordinat', 'Koordinat',        'Koordinat lat/long suatu tempat'],
  ['timezone_info','Info Timezone', 'Info timezone suatu kota'],
  ['altitude',  'Ketinggian',       'Ketinggian suatu tempat dari laut'],
  ['province_id','Info Provinsi ID','Info provinsi di Indonesia'],
  ['kota_id',   'Info Kota ID',     'Info kota/kabupaten Indonesia'],
  ['wisata',    'Tempat Wisata',    'Tempat wisata di Indonesia'],
  ['wisata_world','Wisata Dunia',   'Tempat wisata terkenal di dunia'],
  ['hotel_rec', 'Rekomendasi Hotel','Rekomendasi hotel di kota tertentu'],
  ['restaurant_rec','Resto Terdekat','Rekomendasi restoran terdekat'],
  ['airport',   'Info Bandara',     'Info dan kode bandara'],
  ['flight_track','Tracking Pesawat','Track posisi pesawat real-time'],
  ['ship_track','Tracking Kapal',  'Track posisi kapal'],
  ['bus_route', 'Rute Bus',         'Rute transportasi bus kota'],
  ['mrt_route', 'Rute MRT/LRT',     'Rute MRT/LRT Jakarta dan kota lain'],
  ['benua',     'Info Benua',       'Info benua-benua di dunia'],
  ['lautan',    'Info Lautan',       'Info samudra dan lautan di dunia'],
  ['gunung',    'Info Gunung',      'Info gunung tertinggi di dunia/Indonesia'],
  ['sungai',    'Info Sungai',      'Info sungai terpanjang di dunia'],
  ['danau',     'Info Danau',       'Info danau terbesar di dunia'],
  ['pulau',     'Info Pulau',       'Info pulau-pulau besar di Indonesia'],
  ['warganegaraan','Kewarganegaraan','Info kewarganegaraan negara tertentu'],
  ['bahasa_negara','Bahasa Negara', 'Bahasa resmi suatu negara'],
  ['agama_negara','Agama Negara',   'Info agama di berbagai negara'],
  ['matauang',  'Mata Uang Negara', 'Mata uang resmi suatu negara'],
])

// ══════════════════════════════════════════
// 25. SPORTS  ~80 fitur
// ══════════════════════════════════════════
batch('sports', [
  ['sepakbola', 'Berita Sepak Bola','Berita dan hasil sepak bola terkini'],
  ['skor',      'Skor Live',        'Skor pertandingan live'],
  ['klasemen',  'Klasemen Liga',    'Klasemen liga sepak bola'],
  ['jadwal_bola','Jadwal Pertandingan','Jadwal pertandingan sepak bola'],
  ['liga_id',   'Liga Indonesia',   'Info Liga 1/2 Indonesia'],
  ['epl',       'English Premier League','Info EPL'],
  ['laliga',    'La Liga Spanyol',  'Info La Liga Spanyol'],
  ['seriea',    'Serie A Italia',   'Info Serie A Italia'],
  ['bundesliga','Bundesliga Jerman','Info Bundesliga Jerman'],
  ['ligue1',    'Ligue 1 Prancis',  'Info Ligue 1 Prancis'],
  ['ucl',       'UEFA Champions League','Info UCL'],
  ['worldcup',  'Piala Dunia',      'Info Piala Dunia FIFA'],
  ['asiacup',   'Piala Asia',       'Info Piala Asia AFC'],
  ['asean_cup', 'Piala ASEAN',      'Info Piala ASEAN'],
  ['badminton', 'Berita Badminton', 'Berita bulutangkis Indonesia'],
  ['basket',    'Berita Basket',    'Berita basket NBA/Indonesia'],
  ['nba_score', 'Skor NBA',         'Skor dan hasil NBA'],
  ['tenis',     'Berita Tenis',     'Berita tenis ATP/WTA'],
  ['f1',        'Formula 1',        'Berita dan jadwal F1'],
  ['moto_gp',   'MotoGP',           'Berita dan jadwal MotoGP'],
  ['tinju',     'Berita Tinju',     'Berita dan jadwal tinju'],
  ['mma',       'MMA/UFC',          'Berita dan jadwal MMA/UFC'],
  ['esports_id','Esports Indonesia','Berita esports Indonesia'],
  ['valorant',  'Valorant',         'Info game Valorant (pro scene)'],
  ['mlbb',      'Mobile Legends',   'Info Mobile Legends pro scene'],
  ['freefire',  'Free Fire',        'Info Free Fire pro scene'],
  ['bgmi',      'PUBG Mobile',      'Info PUBG Mobile'],
  ['dota2',     'Dota 2',           'Info Dota 2 pro scene'],
  ['csgo',      'CS:GO',            'Info CS:GO pro scene'],
  ['lol',       'League of Legends','Info LoL pro scene'],
])

// ══════════════════════════════════════════
// 26. MISC / OTHER  ~100 fitur
// ══════════════════════════════════════════
batch('other', [
  ['help',      'Bantuan',          'Tampilkan panduan penggunaan bot'],
  ['about',     'Tentang Bot',      'Tentang dan versi bot ini'],
  ['changelog', 'Changelog',        'Perubahan versi terbaru bot'],
  ['invite',    'Link Invite',      'Buat link undangan WhatsApp'],
  ['sosmed',    'Sosial Media',     'Link sosial media owner/bot'],
  ['report_bug','Lapor Bug',        'Laporkan bug ke developer'],
  ['suggest',   'Saran Fitur',      'Kirim saran fitur baru'],
  ['rating',    'Beri Rating',      'Beri rating untuk bot ini'],
  ['donate',    'Donasi',           'Info cara donasi ke developer'],
  ['premium_info','Info Premium',   'Info paket dan harga premium'],
  ['id',        'ID Pengirim',      'Lihat JID/ID WhatsApp kamu'],
  ['tid',       'ID Grup',          'Lihat JID grup saat ini'],
  ['msgid',     'ID Pesan',         'Lihat ID pesan yang di-reply'],
  ['mediainfo', 'Info Media',       'Info metadata media yang dikirim'],
  ['storedb',   'Status Database',  'Status database bot saat ini'],
  ['clearjunk', 'Bersih Cache',     'Bersihkan file cache sementara'],
  ['meminfo',   'Info Memori',      'Info penggunaan memori bot'],
  ['diskinfo',  'Info Disk',        'Info penggunaan disk server'],
  ['netinfo',   'Info Jaringan',    'Info koneksi jaringan bot'],
  ['colortest', 'Test Warna',       'Test tampilan warna di WA'],
  ['emojilist', 'Daftar Emoji',     'Daftar emoji populer dan artinya'],
  ['emojiinfo', 'Info Emoji',       'Info detail suatu emoji'],
  ['keyboard_shortcut','Shortcut WA','Shortcut keyboard WhatsApp Web'],
  ['wa_tips',   'Tips WhatsApp',    'Tips dan trik tersembunyi WA'],
  ['privacy_tips','Tips Privasi',   'Tips melindungi privasi di WA'],
  ['scam_check','Cek Penipuan',     'Cek apakah nomor/link penipuan'],
  ['hoax_check','Cek Hoaks',        'Cek berita hoaks dari database'],
  ['fact_check','Fact Check',       'Verifikasi fakta klaim tertentu'],
  ['bpom_check','Cek BPOM',         'Cek registrasi produk di BPOM'],
  ['halal_check','Cek Halal',       'Cek sertifikasi halal produk MUI'],
  ['npwp_check','Cek NPWP',         'Validasi format NPWP'],
  ['ktp_check', 'Validasi KTP',     'Validasi dan decode NIK KTP'],
  ['bpjs_check','Cek BPJS',         'Cek tagihan BPJS Kesehatan'],
  ['listrik_pln','Tagihan PLN',     'Cek tagihan listrik PLN'],
  ['pdam_check','Tagihan PDAM',     'Cek tagihan air PDAM'],
  ['telpsel',   'Cek Telkomsel',    'Cek info nomor Telkomsel'],
  ['indosat',   'Cek Indosat',      'Cek info nomor Indosat/IM3'],
  ['xl',        'Cek XL',           'Cek info nomor XL/Axis'],
  ['tri',       'Cek 3 (Tri)',      'Cek info nomor 3 (Tri)'],
  ['smartfren', 'Cek Smartfren',    'Cek info nomor Smartfren'],
  ['countdown', 'Hitung Mundur',    'Hitung mundur ke tanggal tertentu'],
  ['countup',   'Hitung Naik',      'Hitung waktu sejak tanggal tertentu'],
  ['meeting',   'Buat Meeting',     'Generate link Google Meet'],
  ['zoom',      'Buat Zoom Link',   'Info cara buat Zoom meeting'],
  ['classroom', 'Google Classroom', 'Tips penggunaan Google Classroom'],
  ['gdoc_template','Template Doc',  'Template dokumen Google Docs populer'],
  ['cv_template','Template CV',     'Template CV siap pakai'],
  ['surat_template','Template Surat','Template surat resmi Indonesia'],
  ['proposal_template','Template Proposal','Template proposal kegiatan'],
])

// ═══════════════════════════════════════════
// TOTAL CHECK
// ═══════════════════════════════════════════
window.RENGU_FEATURES = R

// Category metadata
window.RENGU_CATS = {
  tools:         { icon:'🔧', label:'Tools & Utility',       color:'#3b82f6' },
  translator:    { icon:'🌐', label:'Translator',            color:'#06b6d4' },
  ai:            { icon:'🤖', label:'AI & Chatbot',          color:'#8b5cf6' },
  image:         { icon:'🖼️', label:'Image Editing',         color:'#ec4899' },
  sticker:       { icon:'🎨', label:'Sticker',               color:'#f97316' },
  downloader:    { icon:'⬇️', label:'Downloader',            color:'#10b981' },
  game:          { icon:'🎮', label:'Games',                 color:'#84cc16' },
  rpg:           { icon:'⚔️', label:'RPG System',            color:'#ef4444' },
  anime:         { icon:'🌸', label:'Anime & Manga',         color:'#f9a8d4' },
  fun:           { icon:'😂', label:'Fun & Random',          color:'#fbbf24' },
  group:         { icon:'👥', label:'Group Admin',           color:'#60a5fa' },
  owner:         { icon:'👑', label:'Owner Commands',        color:'#f59e0b' },
  store:         { icon:'🛒', label:'Store & Economy',       color:'#34d399' },
  stalk:         { icon:'🔍', label:'Stalk & Social',        color:'#94a3b8' },
  sound:         { icon:'🎵', label:'Sound & Audio',         color:'#a78bfa' },
  convert:       { icon:'🔄', label:'Convert & Format',      color:'#14b8a6' },
  search:        { icon:'🔎', label:'Search',                color:'#6366f1' },
  education:     { icon:'📚', label:'Education',             color:'#0ea5e9' },
  islam:         { icon:'☪️', label:'Islam & Agama',         color:'#22c55e' },
  developer:     { icon:'💻', label:'Developer Tools',       color:'#64748b' },
  health:        { icon:'❤️', label:'Health & Wellness',     color:'#fb7185' },
  food:          { icon:'🍜', label:'Food & Culinary',       color:'#fde68a' },
  entertainment: { icon:'🎬', label:'Entertainment',         color:'#c084fc' },
  geography:     { icon:'🌍', label:'Geography & Travel',    color:'#4ade80' },
  sports:        { icon:'⚽', label:'Sports',               color:'#38bdf8' },
  other:         { icon:'📦', label:'Other & Misc',          color:'#6b7280' },
}

console.log('✓ RENGU Features loaded:', R.length, 'features')

})()
